uselagoon/lagoon-charts

- charts/lagoon-logging/Chart.yaml
- charts/lagoon-logging/templates/logs-dispatcher.fluent-conf.configmap.yaml
Fixes the tag wildcard matching so that openshift router logs are correctly matched.
Closes: #12
> Fix router log routing

- charts/lagoon-core/Chart.yaml
- charts/lagoon-core/templates/_helpers.tpl
- charts/lagoon-core/values.yaml
This allows subcharts to correctly determine the fullname of the parent chart.
> Properly handle lagoon-core release naming in subcharts

- charts/lagoon-core/Chart.yaml
- charts/lagoon-core/README.md
- charts/lagoon-core/ci/linter-values.yaml
- charts/lagoon-core/templates/NOTES.txt
- charts/lagoon-core/templates/_helpers.tpl
- charts/lagoon-core/templates/auth-server.service.yaml
- charts/lagoon-core/templates/broker.serviceaccount.yaml
- charts/lagoon-core/templates/keycloak.secret.yaml
- charts/lagoon-core/templates/ssh-portal.clusterrole.yaml
- charts/lagoon-core/templates/ssh-portal.clusterrolebinding.yaml
- charts/lagoon-core/templates/ssh-portal.deployment.yaml
- charts/lagoon-core/templates/ssh-portal.secret.yaml
- charts/lagoon-core/templates/ssh-portal.service.yaml
- charts/lagoon-core/templates/ssh-portal.serviceaccount.yaml
- charts/lagoon-core/values.yaml
This PR adds ssh-portal support to the chart. See https://github.com/amazeeio/lagoon/pull/2179
It also adds fixes for the SSH service.
TODO:
> Add ssh-portal to lagoon-core

- charts/lagoon-core/Chart.yaml
- charts/lagoon-core/ci/linter-values.yaml
- charts/lagoon-core/templates/api.deployment.yaml
- charts/lagoon-core/templates/api.secret.yaml
- charts/lagoon-core/templates/keycloak.service.yaml
- charts/lagoon-core/values.yaml
Environment variables for various services were missing from the API.
Also closes: #23
> Add some more API environment variables

- charts/lagoon-core/Chart.yaml
- charts/lagoon-core/templates/api.deployment.yaml
- charts/lagoon-core/templates/webhooks2tasks.deployment.yaml
- charts/lagoon-core/values.yaml
These extra variables are optional depending on Lagoon service integrations.
> Optional service integration

- charts/lagoon-core/Chart.yaml
- charts/lagoon-core/templates/api-db.statefulset.yaml
- charts/lagoon-core/templates/api.deployment.yaml
- charts/lagoon-core/templates/auth-server.deployment.yaml
- charts/lagoon-core/templates/auto-idler.deployment.yaml
- charts/lagoon-core/templates/backup-handler.deployment.yaml
- charts/lagoon-core/templates/broker.statefulset.yaml
- charts/lagoon-core/templates/controllerhandler.deployment.yaml
- charts/lagoon-core/templates/drush-alias.deployment.yaml
- charts/lagoon-core/templates/keycloak-db.statefulset.yaml
- charts/lagoon-core/templates/keycloak.deployment.yaml
- charts/lagoon-core/templates/logs-db-curator.deployment.yaml
- charts/lagoon-core/templates/logs2email.deployment.yaml
- charts/lagoon-core/templates/logs2microsoftteams.deployment.yaml
- charts/lagoon-core/templates/logs2rocketchat.deployment.yaml
- charts/lagoon-core/templates/logs2slack.deployment.yaml
- charts/lagoon-core/templates/ssh-portal.deployment.yaml
- charts/lagoon-core/templates/ssh.deployment.yaml
- charts/lagoon-core/templates/ui.deployment.yaml
- charts/lagoon-core/templates/webhook-handler.deployment.yaml
- charts/lagoon-core/templates/webhooks2tasks.deployment.yaml
- charts/lagoon-core/values.yaml
- allow to globaly overwrite imageTag 
- define `fsGroup: 0` for `api-d`b and `keycloak-db` this makes sure the persistent storage actually has the file permissions correctly (writeable for group)
> ImageTag & persistent storage permission fix

- .github/workflows/lint-test.yaml
- .github/workflows/release.yaml
- ct.yaml
This PR removes the `check-version-increment` step from linting - which means that linting will run on every push or pull request
Instead the `check-version-increment` step runs ahead of a release, which will only be triggered on a tag push - so if you tag a release and the chart version isn't changed, the release will fail.  You'll have to push a new chart version and retag.
It's not currently smart enough to know what or how to tag charts - having multiple charts in the same repo makes this harder.
> Enable Linting without check-version, and only release on tag push

- ct.yaml
Reverts the last of the functional changes made in #93, most of which have already been reverted.
> Enforce version bump in lint

- charts/lagoon-core/Chart.yaml
- charts/lagoon-core/templates/api.deployment.yaml
- realized that the api actually needs API_HOST after all
- harbor password is stored in a secret so we can load it from there.
> add API_HOST back to api, load harbor password from secret

- charts/lagoon-core/Chart.yaml
- charts/lagoon-core/templates/api.deployment.yaml
- charts/lagoon-core/values.yaml
This PR adds the `HarborAPIVersion` value, which allows us to maintain backwards compatibility with Harbor v1 while also supporting Harbor v2 as well. This PR works in tandem with the variable introduced in [Lagoon PR #2231](https://github.com/amazeeio/lagoon/issues/2231) to provide this functionality.
> Add Backwards Compatibility Support for Harbor v1 API

- charts/lagoon-logging/Chart.lock
- charts/lagoon-logging/Chart.yaml
- charts/lagoon-logging/templates/clusterflow.yaml
This requires an update to the CRD as per
https://github.com/banzaicloud/logging-operator/releases/tag/3.6.0
Closes: #57
> Bump the logging-operator dependency version

- .github/workflows/lint-test.yaml
We were using a custom chart-testing image, but the required changes are available in [3.1.0](https://github.com/helm/chart-testing/releases/tag/v3.1.0)+.
Specifically we needed:
* https://github.com/helm/chart-testing/pull/250
* https://github.com/helm/chart-testing/pull/252
* https://github.com/helm/chart-testing/pull/253
* https://github.com/helm/chart-testing/pull/260
Closes: #108
> Rely on upstream chart-testing image

- charts/lagoon-logging/Chart.yaml
- charts/lagoon-logging/values.yaml
- charts/lagoon-logs-concentrator/Chart.yaml
- charts/lagoon-logs-concentrator/values.yaml
Use a release image tag instead of `master` or some other branch build in the logging charts.
> Remove logging image overrides

- charts/lagoon-core/Chart.yaml
- charts/lagoon-core/ci/linter-values.yaml
- charts/lagoon-core/templates/api.deployment.yaml
- charts/lagoon-core/templates/api.secret.yaml
- charts/lagoon-core/templates/webhooks2tasks.deployment.yaml
- charts/lagoon-core/values.yaml
Some secrets were directly referenced as environment variables. Avoid this information leak by mounting them via secrets.
Closes: #112
> Refactor secrets

- charts/lagoon-core/Chart.yaml
- charts/lagoon-core/templates/broker.servicemonitor.yaml
hotfix for wrong `apiVersion` of lagoon-core broker.servicemonitor.yaml
> hotfix: correct apiVersion for ServiceMonitor

- .github/workflows/lint-test.yaml
- .github/workflows/release.yaml
The `stable` helm repository is deprecated and is being removed in a few weeks. The URL has now changed.
A follow-up PR will remove all usage of the `stable` repo. See also https://github.com/uselagoon/lagoon-charts/issues/132
> Update required repositories in test and release workflows

- charts/lagoon-logging/Chart.yaml
- charts/lagoon-logging/templates/logs-dispatcher.fluent-conf.configmap.yaml
lagoon projectnames with underlines are deprecated
unfortunately we still have some projects with underlines, but no auxiliary systems (kibana, billing, etc.) support them, so we change underlines to dashes when creating the indexes
> Underline to dashes

- charts/lagoon-logging/Chart.yaml
- charts/lagoon-logging/templates/logs-dispatcher.fluent-conf.configmap.yaml
There are a couple of issues with the change from https://github.com/uselagoon/lagoon-charts/pull/140
1. the result of `record.dig()` may be nil, so calling `sub()` will raise an exception (and cause the worker thread to restart). This PR fixes that by using the lonely operator.
2. `sub()` only replaces the _first_ match. This PR changes it to use `gsub()` instead.
The result of this logic is:
* the project part of the index names in Elasticsearch will have their underscores replaced by hyphens. 
* the field `lagoon_sh/project` within the log record will still have the original project name with any underscores.
Is that the way it should be @Schnitzel?
> Safe underscore replacement

- .github/workflows/release.yaml
chart-releaser-action v1.1.0 seems to have broken the previous automatic workflow.
> Manually add required repository for chart-releaser

- charts/lagoon-remote/Chart.yaml
- charts/lagoon-remote/crds/lagoonBuild.yaml
- charts/lagoon-remote/values.yaml
The Lagoon Build Deploy controller v0.1.4 supports Openshift now, this PR adds some notes in the `values.yaml` file with information around this. Also updated the CRD to the latest version.
Quick run down on the changes:
The controller supports defining the build image that gets injected into a Lagoon Build, as this will no longer be handled by Lagoon core in the future. 
Currently Lagoon will inject the `image` into the build spec and send that to the controller, and the controller will use what is in the spec before it uses what the controller has defined. This is on purpose, as there may be changes in Lagoon in the future that could allow for custom build images to be injected directly into the build per project/environment and override what is defined by the controller. 
The …
> Build Deploy controller Openshift and Build Image support

- charts/lagoon-core/Chart.yaml
- charts/lagoon-core/ci/linter-values.yaml
- charts/lagoon-core/templates/storage-calculator.deployment.yaml
- charts/lagoon-core/values.yaml
- charts/lagoon-logging/Chart.yaml
- charts/lagoon-logging/ci/linter-values.yaml
- charts/lagoon-logging/templates/logs-dispatcher.statefulset.yaml
- charts/lagoon-logging/templates/logs-tee.deployment.yaml
- charts/lagoon-logging/values.yaml
- charts/lagoon-logs-concentrator/Chart.yaml
- charts/lagoon-logs-concentrator/ci/linter-values.yaml
- charts/lagoon-logs-concentrator/templates/statefulset.yaml
- charts/lagoon-logs-concentrator/values.yaml
- charts/lagoon-remote/Chart.yaml
- charts/lagoon-remote/ci/linter-values.yaml
- charts/lagoon-remote/values.yaml
- charts/lagoon-test/Chart.yaml
- charts/lagoon-test/ci/linter-values.yaml.tpl
- charts/lagoon-test/templates/local-api-data-watcher-pusher.deployment.yaml
- charts/lagoon-test/templates/local-git.deployment.yaml
- charts/lagoon-test/templates/tests/test-suite.yaml
- charts/lagoon-test/values.yaml
This PR references the `testlagoon/` dockerhub organisation - and sets the `:main` branch for images.
It also adds the necessary logic into all the charts to allow for a top-level .Values.imageTag to be set to override the default image tag behaviour.
Once we have a tagged release of `uselagoon/`-based images, we should switch to them, and then override them with testlagoon images via an additional values.yaml file or similar.
> Reference correct generation Lagoon images and support .Values.imageTag

- Makefile
- charts/lagoon-remote/Chart.yaml
- charts/lagoon-remote/crds/dioscuri.yaml
- charts/lagoon-remote/crds/lagoonBuild.yaml
- charts/lagoon-remote/templates/_helpers.tpl
- charts/lagoon-remote/templates/dioscuri.clusterrole.yaml
- charts/lagoon-remote/templates/dioscuri.clusterrolebinding.yaml
- charts/lagoon-remote/templates/dioscuri.deployment.yaml
- charts/lagoon-remote/templates/dioscuri.role.yaml
- charts/lagoon-remote/templates/dioscuri.rolebinding.yaml
- charts/lagoon-remote/templates/dioscuri.service.yaml
- charts/lagoon-remote/templates/dioscuri.serviceaccount.yaml
- charts/lagoon-remote/templates/lagoon-build-deploy.deployment.yaml
- charts/lagoon-remote/values.yaml
- charts/lagoon-test/Chart.yaml
- charts/lagoon-test/templates/tests/test-suite.yaml
This PR combines a few different changes:
* Add [dioscuri](https://github.com/amazeeio/dioscuri) to the lagoon-remote chart to support active-standby in Lagoon.
* Refactor the lagoon-remote values.yaml for consisitency.
* Add the active-standby test suite to CI.
* Disable the ingress-nginx admission controller webhook in CI to work around https://github.com/amazeeio/dioscuri/issues/10. Once that is fixed in dioscuri this change needs to be reverted (https://github.com/uselagoon/lagoon-charts/issues/168).
Closes: #160, partially addresses #118.
> Add support for active-standby to lagoon-remote chart

- charts/lagoon-logging/Chart.yaml
- charts/lagoon-logging/templates/logs-dispatcher.fluent-conf.configmap.yaml
While reviewing #156 and debugging some other error messages in the `logs-concentrator` I realised that the consolidation syntax was wrong.
Going back to my original testing for this I discovered that this is actually an issue with the upstream fluentd `record_modifier` plugin documentation and test suite. There's a PR for upstream here that explains the issue: https://github.com/repeatedly/fluent-plugin-record-modifier/pull/56
So I incorporated the changes for #156 and also fixed the syntax. I hope you don't mind that I took some config snippets from your PR @Schnitzel!
Supersedes / Closes: #156
> Consolidation fixes

- .github/workflows/test-suite.yaml
- Makefile
- charts/lagoon-core/Chart.yaml
- charts/lagoon-core/templates/webhooks2tasks.deployment.yaml
- charts/lagoon-remote/Chart.yaml
- charts/lagoon-remote/templates/lagoon-build-deploy.deployment.yaml
- charts/lagoon-remote/values.yaml
- charts/lagoon-test/Chart.yaml
- charts/lagoon-test/ci/linter-values.yaml.tpl
In CI we need to be able to override the build-deploy-dind image so that the one built locally can be used.
This PR:
* Adds the option for overriding the image in `lagoon-remote`
* Adds the option to pass the image in a variable in the `Makefile`
This change is in support of CI in amazeeio/lagoon.
> Add option to override the build-deploy-dind image in CI

- .github/workflows/test-suite.yaml
- Makefile
- charts/lagoon-test/Chart.yaml
- charts/lagoon-test/ci/linter-values.yaml.tpl
- test-suite.kind-config.yaml
- test-suite.kind-config.yaml.tpl
This PR makes it possible to run chart testing using a local registry.
This is in support of Lagoon 2.0 CI.
> Support local registry

- README.md
- charts/lagoon-build-deploy/.helmignore
- charts/lagoon-build-deploy/Chart.yaml
- charts/lagoon-build-deploy/ci/linter-values.yaml
- charts/lagoon-build-deploy/crds/lagoonBuild.yaml
- charts/lagoon-build-deploy/templates/NOTES.txt
- charts/lagoon-build-deploy/templates/_helpers.tpl
- charts/lagoon-build-deploy/templates/clusterrolebinding.yaml
- charts/lagoon-build-deploy/templates/deployment.yaml
- charts/lagoon-build-deploy/templates/secret.yaml
- charts/lagoon-build-deploy/templates/service.yaml
- charts/lagoon-build-deploy/templates/serviceaccount.yaml
- charts/lagoon-build-deploy/values.yaml
- default.ct.yaml
- test-suite-lint.ct.yaml
This PR creates a separate chart for lagoon-build-deploy. Eventually this will be used as a dependency in lagoon-remote.
Partially addresses https://github.com/uselagoon/lagoon-charts/issues/175.
> Add lagoon-build-deploy chart

- .github/workflows/test-suite.yaml
- Makefile
- charts/lagoon-build-deploy/Chart.yaml
- charts/lagoon-build-deploy/templates/deployment.yaml
- charts/lagoon-build-deploy/values.yaml
- charts/lagoon-core/Chart.yaml
- charts/lagoon-core/ci/linter-values.yaml
- charts/lagoon-core/values.yaml
- charts/lagoon-logging/Chart.yaml
- charts/lagoon-logging/ci/linter-values.yaml
- charts/lagoon-logging/values.yaml
- charts/lagoon-logs-concentrator/Chart.yaml
- charts/lagoon-logs-concentrator/ci/linter-values.yaml
- charts/lagoon-logs-concentrator/values.yaml
- charts/lagoon-remote/Chart.yaml
- charts/lagoon-remote/ci/linter-values.yaml
- charts/lagoon-remote/values.yaml
- charts/lagoon-test/Chart.yaml
- charts/lagoon-test/values.yaml
so the goals here:
* Set the charts to use the named release of Lagoon (2.0.0-alpha.1) from the uselagoon repo as a default
* Allow the makefile (or command line) to provide a different repository (testlagoon) or tag (main etc) for the images
* Be able to locally build the individual namespaces (core, remote, tests) without having to rebuild everything - again using the common repository/image settings
* Fix up the variable naming in the build-deploy-dind variable overwrite (not working yet)
> replace Testlagoon images with uselagoon+tag, smoother local dev

- .github/workflows/test-suite.yaml
- Makefile
- charts/lagoon-build-deploy/Chart.yaml
- charts/lagoon-build-deploy/crds/lagoonBuild.yaml
`LagoonBuilds` needs to have `spec.pullrequests.number` to be a string, this updates:
- CRD with this update
- lagoon-build-deploy update amazeeio/lagoon-kbd#22
> update lagoon-build-deploy pullrequest.number to be a string

- charts/lagoon-build-deploy/Chart.yaml
- charts/lagoon-build-deploy/templates/deployment.yaml
- charts/lagoon-build-deploy/values.yaml
- charts/lagoon-remote/Chart.yaml
- charts/lagoon-remote/values.yaml
the lagoon-build-deploy controller needs to know the SSH and API Host and ports to properly run lagoon tasks, this allows it inject them.
> allow to inject task environment variables

- charts/lagoon-logging/Chart.lock
- charts/lagoon-logging/Chart.yaml
- charts/lagoon-logging/templates/logs-dispatcher.fluent-conf.configmap.yaml
- charts/lagoon-logging/values.yaml
This PR:
* bumps the logs-dispatcher image version to support sumologic output.
* bumps the logging-operator dependency version for maintenance reasons.
* avoid stripping the `message` field, since this appears to depend on the container runtime in use(?): https://github.com/banzaicloud/logging-operator/blob/chart/logging-operator/3.9.0/pkg/sdk/model/types/types.go#L28-L34
Closes: #165
> lagoon-logging sumologic support and dependency maintenance

- charts/lagoon-logging/Chart.yaml
- charts/lagoon-logging/ci/linter-values.yaml
- charts/lagoon-logging/values.yaml
The update on the default tag in #204 neglected to take into account the image the tag was attached to.
In addition this issue exposed a problem in our CI `linter-values.yaml`, so this PR fixes that too.
> Revert logs dispatcher tag

- charts/lagoon-logging/Chart.yaml
- charts/lagoon-logging/templates/logs-dispatcher.fluent-conf.configmap.yaml
- charts/lagoon-logging/values.yaml
This PR makes it possible to inject raw fluentd configuration snippets into the logs-dispatcher's `fluent.conf`.
This is useful if, for example, you want to be able to direct logs to different `<match>...</match>` endpoints by tag.
> Logging extra conf

- charts/lagoon-gatekeeper/Chart.yaml
- charts/lagoon-gatekeeper/templates/_helpers.tpl
- charts/lagoon-gatekeeper/templates/constraint.job.yaml
- charts/lagoon-gatekeeper/templates/psp-pods-allowed-user-ranges.constraint.yaml
When used as a subchart, names in lagoon-gatekeeper can hit the 63 character limit. This PR adds a function to safely suffix the chart fullname without breaking 63 chars.
> Fix name length issues in lagoon-gatekeeper

- .github/workflows/lint-test.yaml
- charts/lagoon-remote/Chart.lock
- charts/lagoon-remote/Chart.yaml
- charts/lagoon-remote/ci/linter-values.yaml
- charts/lagoon-remote/values.yaml
This PR adds lagoon-gatekeeper as a lagoon-remote dependency, disabled by default, but enabled in CI.
lagoon-gatekeeper runs in audit-only mode by default so it does not block admission of pods to the cluster.
> Lagoon gatekeeper integration with lagoon-remote

- Makefile
This change allows using a different image for the `lagoon-builddeploy` controller image.
> Add ability to override the build-deploy image repository

- charts/lagoon-build-deploy/Chart.yaml
Lagoon Build Deploy released a new version [v0.1.7](https://github.com/amazeeio/lagoon-kbd/releases/tag/v0.1.7)
> Bump lagoon-build-deploy to use latest version

- charts/lagoon-remote/Chart.lock
- charts/lagoon-remote/Chart.yaml
This PR just updates the dependencies of `lagoon-remote` to the latest point releases.
> Bump dependencies of lagoon-remote

- Makefile
- charts/lagoon-build-deploy/Chart.yaml
- charts/lagoon-build-deploy/templates/deployment.yaml
- charts/lagoon-build-deploy/values.yaml
This is required for testing https://github.com/amazeeio/lagoon/pull/2481 and is disabled by default.
> Add experimental support for rootless build pods

- Makefile
- charts/lagoon-core/Chart.yaml
- charts/lagoon-core/values.yaml
Use consistent user/group IDs for workloads in lagoon-core too.
This isn't enforced, just better than using some other random IDs.
~Draft until the associated PR is accepted into amazeeio/lagoon.~
> Lagoon core user consistency

- .github/workflows/lint-test.yaml
- .github/workflows/test-suite.yaml
This PR adds a logic step to the k8s cluster steps that will perform them even if there are no chart changes.
This may be needed to test logic in the makefiles etc.  To use it, allow the skipped run of the GitHub action to complete, then add the `needs-testing` label, and trigger a new run for the PR.
> add needs-testing label logic to github actions

- Makefile
This reverts commit ea216852f70cc2ceec65f0e5f3e2ff891b6fc4ab.
That commit temporarily overrode the Lagoon image repository and tag used for testing to work around https://github.com/amazeeio/lagoon/issues/2533. Now that issue is fixed in Lagoon `main`, we can revert back to the default image repository and tag.
> Revert back to default Lagoon images

- .github/workflows/test-suite.yaml
- Makefile
This will mean that dependencies will not match the lock file!
> Don't update dependencies in lagoon-remote during CI

- charts/lagoon-core/Chart.yaml
- charts/lagoon-core/README.md
- charts/lagoon-core/values.yaml
was called `s3SecretAccessKey` in the values.yaml, but the template actually searches for `s3FilesSecretAccessKey`
> fix wrong s3FilesSecretAccessKey name

- charts/lagoon-build-deploy/Chart.yaml
- charts/lagoon-build-deploy/templates/deployment.yaml
- charts/lagoon-build-deploy/values.yaml
This PR adds experimental support for feature flags to the lagoon-build-deploy chart.
This uses the flags from https://github.com/amazeeio/lagoon-kbd/pull/40
> Add feature flags to the lagoon-build-deploy chart

- charts/lagoon-logging/Chart.yaml
- charts/lagoon-logging/templates/logs-dispatcher.fluent-conf.configmap.yaml
The Kubernetes fields (namespace etc.) are useful for cross-indexing between log indices.
> Retain kubernetes fields in application logs

- charts/lagoon-logging/Chart.yaml
- charts/lagoon-logging/templates/logs-dispatcher.statefulset.yaml
Third-party exporters can be slow or otherwise cause TCP probes to take a while. We don't need to kill pods for slow connections.
> Make the logs-dispatcher probes more forgiving

- charts/lagoon-logging/Chart.yaml
- charts/lagoon-logging/templates/logs-dispatcher.fluent-conf.configmap.yaml
- charts/lagoon-logging/values.yaml
The old logic was plain broken if tlsVerifyHostname was set to `false`.
> Allow hostname to be ignored in lagoon-logging TLS verification

- charts/lagoon-logging/Chart.yaml
- charts/lagoon-logging/ci/linter-values.yaml
- charts/lagoon-logging/templates/logging.yaml
- charts/lagoon-logging/values.yaml
We don't have to manually configure service monitors any more because they are supported by the operator chart.
> Rely on built-in operator service monitors

- charts/lagoon-logs-concentrator/Chart.yaml
- charts/lagoon-logs-concentrator/templates/fluent-conf.configmap.yaml
- charts/lagoon-logs-concentrator/values.yaml
It can be useful to disable Elasticsearch certificate verification for local testing.
> Add option to disable Elasticsearch certificate verification

- charts/lagoon-build-deploy/Chart.yaml
- charts/lagoon-build-deploy/templates/deployment.yaml
- charts/lagoon-build-deploy/values.yaml
When needing to add `extraArgs` to the builddeploy controller, defining new values in an external template would override the defaults provided in the template, so they need to be defined again wherever the `extraArgs` are defined.
This moves them into the template and frees up `extraArgs` for actual extra arguments.
> Move default args to template for builddeploy controller

- charts/lagoon-logging/Chart.yaml
- charts/lagoon-logging/ci/linter-values.yaml
- charts/lagoon-logging/templates/logging.yaml
- charts/lagoon-logging/values.yaml
This PR allows helm templates to control the replicas for the fluentd pods inside the logging operator.  It keeps the default at 3, but uses 1 for CI (and we would also use 1 for local development)
> allow to control fluentd replicas from values.yaml

- charts/lagoon-remote/Chart.lock
- charts/lagoon-remote/Chart.yaml
> bump lagoon-build-deploy and disocuri to latest chart versions

- Makefile
This PR adds support for controlling feature flags on `lagoon-build-deploy` via the CI Makefile.
> Add support for setting feature flags on lagoon-build-deploy in CI via the Makefile

- charts/lagoon-remote/Chart.yaml
- charts/lagoon-remote/templates/docker-host.pvc.yaml
- charts/lagoon-remote/values.yaml
This PR makes the docker-host PVC storage class configurable through the helm chart values. By default we keep the current behaviour of not defining a storage class so as to fall back to cluster default.
Closes #251
> Docker host storageclass

- charts/lagoon-logs-concentrator/Chart.yaml
- charts/lagoon-logs-concentrator/templates/hpa.yaml
version increment has been set to a minor behind #254 which should be merged first.
> fix StatefulSet typo in logs-concentrator

- .github/dependabot.yml
Tell dependabot to tag any PRs with `needs-testing` so the test suite runs.
> Run tests for dependabot PRs

- charts/lagoon-test/Chart.yaml
- charts/lagoon-test/templates/local-api-data-watcher-pusher.deployment.yaml
- charts/lagoon-test/templates/tests/test-suite.yaml
This PR adds the JWTSECRET to the lagoon-test-test-suite.
This will enable ansible playbooks etc to perform GraphQL mutations in tests to add and delete projects, groups, notifications, and other permissions not available to normal users.
> add JWTSECRET to test-suite

- .github/workflows/test-suite.yaml
- Makefile
- charts/lagoon-core/Chart.yaml
- charts/lagoon-core/README.md
- charts/lagoon-core/ci/linter-values.yaml
- charts/lagoon-core/templates/_helpers.tpl
- charts/lagoon-core/templates/logs2webhook.deployment.yaml
- charts/lagoon-core/templates/logs2webhook.hpa.yaml
- charts/lagoon-core/values.yaml
- charts/lagoon-logging/Chart.yaml
- charts/lagoon-logs-concentrator/Chart.yaml
- charts/lagoon-remote/Chart.yaml
- charts/lagoon-test/Chart.yaml
* It updates the version of Lagoon to https://github.com/uselagoon/lagoon/releases/tag/v2.0.0-rc.1 
* This PR also includes #269 to add the new logs2webhook service in
* It reduces the number of tests performed to those related to Lagoon only (API, Features 1&2, Active/Standby)
* Any other tests can be enabled on a per PR/Branch basis
> update lagoon to v2.0.0-rc.1

- charts/lagoon-test/Chart.yaml
- charts/lagoon-test/templates/test.clusterrolebinding.yaml
This allows the test serviceaccount to list secrets, which is required for some of the CI tests.
> Give the test serviceaccount admin clusterrole

- Makefile
- test-suite.kind-config.calico.yaml.tpl
Make Calico opt-in and rely on the default kindnet otherwise.
This should improve the local testing experience, particularly on Mac.
Closes: #271
> Make Calico CNI plugin optional

- charts/lagoon-remote/Chart.yaml
- charts/lagoon-remote/ci/linter-values.yaml
This chart is currently not very maintained and not used in production.
So lets not run it in CI yet.
> chore: disable gatekeeper chart in CI

- Makefile
In order to avoid messy re-helming once running in lagoon-charts or lagoon-main, lets just enable the UI now.  If it's not used in CI, the overhead shouldn't make an impact.
> enable the UI by default for local development

- Makefile
This PR adds a pair of scripts to help with local development.
`make get-admin-creds` will return the GraphQL token (admin-scoped) and the necessary Keycloak and Lagoon passwords.
`make port-forwards` will automatically create the necessary port forwards for the UI, API and Keycloak to function.
> Add cred & port-forward helper scripts to Makefile

- Makefile
This is a minor nitpick, but just makes all targets consistent.
> Phonify more targets in the Makefile

- charts/lagoon-core/Chart.yaml
- charts/lagoon-core/templates/api.deployment.yaml
- charts/lagoon-core/values.yaml
- charts/lagoon-logging/Chart.yaml
- charts/lagoon-logs-concentrator/Chart.yaml
- charts/lagoon-remote/Chart.yaml
- charts/lagoon-test/Chart.yaml
Updates lagoon-charts for the https://github.com/uselagoon/lagoon/releases/tag/v2.0.0-rc.4 release
Note there was no v2.0.0-rc.3 release, changes are incorporated into v2.0.0-rc.4.
Also resolves an issue with trailing slashes in the UI and Webhook URLs
Closes #283
> v2.0.0-rc.4 AppImage updates for release

- charts/lagoon-core/Chart.yaml
- charts/lagoon-core/templates/api.deployment.yaml
- charts/lagoon-core/templates/auth-server.deployment.yaml
- charts/lagoon-core/templates/backup-handler.deployment.yaml
- charts/lagoon-core/templates/broker.statefulset.yaml
- charts/lagoon-core/templates/drush-alias.deployment.yaml
- charts/lagoon-core/templates/keycloak.deployment.yaml
- charts/lagoon-core/templates/logs-db-curator.deployment.yaml
- charts/lagoon-core/templates/logs2email.deployment.yaml
- charts/lagoon-core/templates/logs2microsoftteams.deployment.yaml
- charts/lagoon-core/templates/logs2rocketchat.deployment.yaml
- charts/lagoon-core/templates/logs2slack.deployment.yaml
- charts/lagoon-core/templates/logs2webhook.deployment.yaml
- charts/lagoon-core/templates/ssh-portal.deployment.yaml
- charts/lagoon-core/templates/ssh.deployment.yaml
- charts/lagoon-core/templates/storage-calculator.deployment.yaml
- charts/lagoon-core/templates/ui.deployment.yaml
- charts/lagoon-core/templates/webhook-handler.deployment.yaml
- charts/lagoon-core/templates/webhooks2tasks.deployment.yaml
- charts/lagoon-core/values.yaml
many of our lagoon services have env variables to control them, while it doesn't make sense to expose each of them via individual helm variables, we can provide a possibility to inject them this way
> allow to inject additional env variables into services

- charts/lagoon-core/Chart.yaml
- charts/lagoon-core/templates/webhooks2tasks.deployment.yaml
This pull request fixes an issue where settings the gitlabAPIToken helm value causes an error rendering the chart yaml.  The {{ include }} for the secret name fails due to it being in a 'with' block.
Closes: #262
> Gitlab API token fix

- Makefile
Disabling the admission controller was a workaround for old versions of Dioscuri, and is no longer necessary.
Closes: https://github.com/uselagoon/lagoon-charts/issues/168
Closes: https://github.com/amazeeio/dioscuri/issues/10
> Re-enable the ingress-nginx admission controller in CI

- charts/lagoon-remote/Chart.yaml
- charts/lagoon-remote/ci/linter-values.yaml
- charts/lagoon-remote/templates/mxout.service.yaml
- charts/lagoon-remote/values.yaml
This service is used by workloads running in-cluster to access a mailserver at a stable domain name.
Closes: #178
> Add optional mxout service to lagoon-remote chart

- charts/lagoon-core/Chart.yaml
- charts/lagoon-core/templates/api-db.statefulset.yaml
- charts/lagoon-core/templates/keycloak-db.statefulset.yaml
- charts/lagoon-core/values.yaml
This PR adds support for the annotations k8up needs to have to backup the `api-db` and `keycloak-db` pods' PVCs in the lagoon-core chart
> Adding k8up annotations to api-db and keycloak-db pods in lagoon-core chart

- charts/lagoon-logging/Chart.yaml
- charts/lagoon-logging/templates/logging.yaml
- charts/lagoon-logging/values.yaml
This makes it possible to collect router logs on clusters with dedicated load balancer nodes.
> Add Lagoon load-balancer tolerations to fluentbit daemonset

- charts/lagoon-logging/Chart.yaml
- charts/lagoon-logging/templates/logs-dispatcher.fluent-conf.configmap.yaml
- charts/lagoon-logging/templates/logs-dispatcher.statefulset.yaml
- charts/lagoon-logging/values.yaml
On newer kubernetes versions the log format has changed enough that the logging chart failed to index router logs and failed to capture container logs properly.
This PR reworks the logs-dispatcher configuration to fix the problem and also improves the way the configuration is structured.
NOTE: this is a breaking change, since it makes 1.19 the minimum kubernetes version. On 1.18 and below, older versions of the chart still work fine.
> Add Kubernetes 1.19 compatibility to lagoon-logging

- charts/lagoon-logging/Chart.yaml
- charts/lagoon-logging/templates/logs-dispatcher.fluent-conf.configmap.yaml
Previously these were being logged to both router-logs-.orphaned and
router-logs-ingress-nginx. Now it's just the latter.
> Avoid logging ingress controller logs twice

- charts/lagoon-logging/Chart.yaml
This PR works around https://github.com/aws/eks-distro/issues/512
Closes: #313
> fix: work around invalid version string returned by EKS

- charts/lagoon-logging/Chart.yaml
- charts/lagoon-logging/templates/logs-dispatcher.fluent-conf.configmap.yaml
This PR add consolidation for the openshift-build-logs.
Test locally using these config files:
fluent.conf:
```
<source>
@type                forward
</source>
<filter lagoon.*.container>
@type record_modifier
<replace>
key index_name
expression /^(?<prefix>container-logs-e2e)-[^-]{10}-[^-]{26}_(?<suffix>.+)$/
replace \k<prefix>_\k<suffix>
</replace>
<replace>
key index_name
expression /^(?<prefix>container-logs-.+-apb)-(?:prov|depr)-[^-]{5}_(?<suffix>.+)$/
replace \k<prefix>_\k<suffix>
</replace>
<replace>
key index_name
expression /^(?<prefix>container-logs-openshift-build-test)-[0-9]+-[^-]{5}$/
replace \k<prefix>
</replace>
</filter>
<match lagoon.**>
@type stdout
</match>
```
sample.log:
```
{"index_name":"container-logs-openshift-build-test"} …
```
> feat: consolidate openshift-build-test container logs

- charts/lagoon-logs-concentrator/Chart.yaml
- charts/lagoon-logs-concentrator/templates/fluent-conf.configmap.yaml
- charts/lagoon-logs-concentrator/templates/secret.yaml
- charts/lagoon-logs-concentrator/templates/statefulset.yaml
- charts/lagoon-logs-concentrator/values.yaml
This PR adds the option to supply a custom CA to the lagoon-logs-concentrator to use to validate the certificate presented by the backing Elasticsearch service.
This is useful when Elasticsearch is presenting a certificate with a private trust root.
> Add option to use a custom CA for Elasticsearch

- charts/lagoon-logging/Chart.lock
- charts/lagoon-logging/Chart.yaml
This missing condition meant that the dependency was always enabled.
Closes: #319
> Fix ability to disable logging-operator dependency

- charts/lagoon-core/Chart.yaml
- charts/lagoon-core/templates/k8up.secret.yaml
our CI only tests with brand new lagoon-core installations, this correctly also handles existing installations of lagoon-core
> Handle already existing lagoon core baas repo pw

- charts/lagoon-core/Chart.yaml
- charts/lagoon-core/templates/k8up.schedule.yaml
This PR adds support for casting the generated bucket name for lagoon-core's k8up schedule into lowercase characters and numbers only. This is required because uppercase characters are not allowed to be used as an S3 bucket name.
> lowercasing the generated lagoon-core k8up bucket name

- charts/lagoon-core/Chart.yaml
- charts/lagoon-core/templates/k8up.schedule.yaml
This PR adds the `baas-` prefix to the bucket name generated for the lagoon-core chart. This is required for the permissions set up for the `k8up` pod's IAM keys to be allowed to access this bucket.
> Adding "baas-" prefix to lagoon-core backup bucket

- charts/lagoon-core/Chart.yaml
- charts/lagoon-core/templates/auth-server.deployment.yaml
All other services that use JWT_SECRET have an annotation to check if the secret has changed to force an update, except auth-server. This service is pretty important too.
> Add secret annotation to auth-server to make sure it is restarted

- charts/lagoon-logging/Chart.yaml
- charts/lagoon-logging/templates/logs-dispatcher.fluent-conf.configmap.yaml
- charts/lagoon-logging/values.yaml
https://github.com/uselagoon/lagoon-charts/pull/310 made a change to lagoon-logging which meant it was no longer compatible with the `docker` container runtime in favour of compatibility with `containerd`.
This PR restores optional `docker` compatibility since it seems `docker` will be with us for a while yet. The default is still assumes `containerd` container runtime.
> Restore optional Docker runtime compatibility to lagoon-logging

- charts/lagoon-logging/Chart.yaml
- charts/lagoon-logging/README.md
- charts/lagoon-logging/ci/linter-values.yaml
- charts/lagoon-logging/templates/_helpers.tpl
- charts/lagoon-logging/templates/cdn-logs-collector.fluent-conf.configmap.yaml
- charts/lagoon-logging/templates/cdn-logs-collector.secret.yaml
- charts/lagoon-logging/templates/cdn-logs-collector.service.yaml
- charts/lagoon-logging/templates/cdn-logs-collector.servicemonitor.yaml
- charts/lagoon-logging/templates/cdn-logs-collector.statefulset.yaml
- charts/lagoon-logging/templates/logs-dispatcher.fluent-conf.configmap.yaml
- charts/lagoon-logging/templates/logs-dispatcher.service.yaml
- charts/lagoon-logging/templates/logs-dispatcher.statefulset.yaml
- charts/lagoon-logging/values.yaml
This adds an optional service to the `lagoon-logging` chart that exposes a port which accepts logs via TLS+TCP. It is disabled by default.
Closes: #324
> Implement CDN logs collection

- charts/lagoon-remote/Chart.yaml
- charts/lagoon-remote/values.yaml
Ensures selinux relabeling is disabled for the docker-host, this would case the container never to start as there can be so many files in the persistent storage.
This only applies for k8s distributions that have selinux enabled (like OpenShift 4). Other k8s distributions should ignore this.
Example in `cri-o` where this is implemented:
https://github.com/cri-o/cri-o/blob/7048f2440217bbb2d6b5b7cfdbad052a4b8527f1/server/container_create_linux.go#L284-L288
> docker-host: disable selinux relabeling

- charts/lagoon-core/Chart.yaml
- charts/lagoon-core/templates/storage-calculator.deployment.yaml
- charts/lagoon-core/values.yaml
> feat: allow cron interval for storage calculator to be adjustable

- .github/workflows/test-suite.yaml
- Makefile
- charts/lagoon-core/Chart.yaml
- charts/lagoon-core/templates/auth-server.service.yaml
- charts/lagoon-core/templates/ssh.service.yaml
- charts/lagoon-core/values.yaml
This PR adds a service.annotations option to the Helm Charts for the lagoon-core ssh and auth-server services.
These annotations can be required by service providers to allow additional configuration options.
Tested as:
```
ssh:
service:
annotations:
service.beta.kubernetes.io/aws-load-balancer-connection-idle-timeout: "600"
```
With the resultant service showing the annotation
```
tobybellwood@pop-os:~/sites/lagoon-main (⎈ |kind-lagoon-local:default) $ kubectl get service lagoon-core-ssh -n lagoon -o yaml
apiVersion: v1
kind: Service
metadata:
annotations:
meta.helm.sh/release-name: lagoon-core
meta.helm.sh/release-namespace: lagoon
service.beta.kubernetes.io/aws-load-balancer-connection-idle-timeout: "600"
creationTimestamp: "2022-02-03T01:23:59Z"
labels:
```
If we need to add …
> Add service.annotations to ssh and auth-server

- charts/lagoon-core/Chart.yaml
- charts/lagoon-logging/Chart.yaml
- charts/lagoon-logging/templates/logs-dispatcher.fluent-conf.configmap.yaml
- charts/lagoon-logs-concentrator/Chart.yaml
- charts/lagoon-remote/Chart.yaml
- charts/lagoon-test/Chart.yaml
lagoon-chart release for https://github.com/uselagoon/lagoon/releases/tag/v2.4.1 (v2.4.0 was skipped, and doesn't have a corresponding lagoon-chart release)
> appVersion: v2.4.1

- Makefile
- charts/lagoon-core/Chart.yaml
- charts/lagoon-core/ci/linter-values.yaml
- charts/lagoon-core/templates/keycloak.deployment.yaml
This PR uses the startup readiness signalling implemented in https://github.com/uselagoon/lagoon/pull/3042 to ensure the Keycloak pod does not become `Ready` in the k8s API until its configuration is complete.
> Use Keycloak startup readiness signalling

- Makefile
When the downstream lagoon builds - it doesn't override the image.tag that is set in the ci/linter-values file - although it overrides the image.repository - this means Kubernetes tries to pull the incorrect image.
This PR temporarily sets the image.tag to the passed imageTag variable to allow it to build properly. These will be removed once the release tag comes out, but are benign if they remain.
> override image.tag for jenkins local-dev

- charts/lagoon-logging/Chart.yaml
- charts/lagoon-logging/templates/logs-dispatcher.fluent-conf.configmap.yaml
Support capturing router logs from a new namespace `sigsci-ingress-nginx`.
Closes: #414
> Add support for router logs capture with SigSci ingress

- charts/lagoon-logging/Chart.lock
- charts/lagoon-logging/Chart.yaml
Bump `logging-operator` to the latest v3.17.3.
> feat: bump logging-operator dependency for lagoon-logging chart

- charts/lagoon-logging/Chart.yaml
- charts/lagoon-logging/README.md
The markdown was written in a way that splits all the ordered lists into separate `<ol>` elements, this isn't great for accessibility. I was also initially confused about the multiple "Openshift Only" sections.
This rewrite renders everything into a single `<ol>` which makes it clearer that the "Openshift Only" instructions are for the installation step they're listed under. I also started the list from 1 instead of 0 since this is a README, not code
> Fix formatting of the install steps in lagoon-logging README

- charts/lagoon-core/Chart.yaml
- charts/lagoon-core/templates/api.deployment.yaml
- charts/lagoon-core/templates/keycloak.secret.yaml
- charts/lagoon-core/values.yaml
This PR allows the ability to define an admin username (other than `admin`) for use with Keycloak, but keeps admin as the default (and won't autogenerate a new name)
> add additional KEYCLOAK_USER secret

- charts/lagoon-core/Chart.yaml
- charts/lagoon-core/templates/keycloak.deployment.yaml
Keycloak sometimes takes >10 minutes to start - I've seen Keycloak get killed before completing configuration both locally and in lagoon-charts CI.
> fix: bump the keycloak startup probe timeout to 15m

- charts/lagoon-logs-concentrator/Chart.yaml
- charts/lagoon-logs-concentrator/ci/linter-values.yaml
- charts/lagoon-logs-concentrator/templates/fluent-conf.configmap.yaml
- charts/lagoon-logs-concentrator/templates/secret.yaml
- charts/lagoon-logs-concentrator/values.yaml
This PR makes it possible to configure an elasticsearch username as part of the lagoon-logs-concentrator chart values.yml file.
> Add the ability to change elasticsearch admin username in logs-concentrator

- charts/lagoon-core/Chart.yaml
- charts/lagoon-core/templates/api.deployment.yaml
- charts/lagoon-core/templates/keycloak.deployment.yaml
- charts/lagoon-core/templates/keycloak.secret.yaml
- charts/lagoon-core/values.yaml
This changes the way the keycloak admin user is added to simplify it and
align it with the way we handle default non-sensitive values in the rest
of the chart.
> fix: refactor keycloak admin user variable

- charts/lagoon-logging/Chart.lock
- charts/lagoon-logging/Chart.yaml
the 3.17.3 release of the logging-operator added HostTailer and EventTailer, enabled by default. If the logging operator is installed without the updated CRDs, it will crashloop.
This PR updates the logging-operator to 3.17.4 where they are [disabled by default](https://github.com/banzaicloud/logging-operator/pull/958), whilst we work out how to automate the update of the CRDs after an update
and yes, we could do this, but I just don't know if we should, or how, or where
```
helm show crds banzaicloud-stable/logging-operator --version 3.17.3 | kubectl apply -f -
```
> update logging operator dependency to 3.17.4

- charts/lagoon-logging/Chart.yaml
- charts/lagoon-logging/templates/logging.yaml
The `logging-operator` chart, which is a dependency of `lagoon-logging`, uses a fluentbit daemonset to collect container logs from the nodes in the cluster. Occasionally fluentbit gets into a state where it appears to be "frozen" and no longer sends logs.
This change enables the default liveness probe for fluentbit which will hopefully restart the pod automatically when it enters this error state.
> Enable liveness probe for fluentbit daemonset

- charts/lagoon-insights-remote/Chart.yaml
- charts/lagoon-insights-remote/values.yaml
corresponding release for https://github.com/uselagoon/insights-remote/releases/tag/v0.0.3
Changes the chart to use the tagged AppVersion instead of latest.
> update to latest lagoon-insights-remote

- charts/lagoon-core/Chart.yaml
- charts/lagoon-logging/Chart.yaml
- charts/lagoon-logs-concentrator/Chart.yaml
- charts/lagoon-remote/Chart.lock
- charts/lagoon-remote/Chart.yaml
- charts/lagoon-test/Chart.yaml
lagoon-charts release to match https://github.com/uselagoon/lagoon/releases/tag/v2.7.1 and update lagoon-remote dependencies
> lagoon-core v2.7.1 updates

- charts/lagoon-logging/Chart.lock
- charts/lagoon-logging/Chart.yaml
This change updates the fluent-bit daemonset from 1.8.15 to 1.9.3 which may help fix some rare log flow reliability issues we have seen in production.
> Bump logging operator dependency in lagoon-logging chart

- charts/lagoon-build-deploy/Chart.yaml
- charts/lagoon-build-deploy/templates/deployment.yaml
- charts/lagoon-build-deploy/values.yaml
As this is now the preferred way to communicate with Harbor, instead of having to specify the harbor arguments to remote-controller as extraArgs, they can now be included in the helm chart values as `harbor.*`
> feat: add harbor values to build-deploy template

- charts/lagoon-core/Chart.yaml
- charts/lagoon-core/templates/api-db.statefulset.yaml
- charts/lagoon-core/templates/broker.statefulset.yaml
- charts/lagoon-core/templates/keycloak-db.statefulset.yaml
- charts/lagoon-core/values.yaml
This change just hard-codes a 10 minute maximum startup timeout on the stateful pods `api-db`, `keycloak-db`, and `broker`.
Is it okay being hard-coded? Or should this be configurable? I'm thinking YAGNI, but there might be a use case.
Closes: #424
Closes: #443
> Startup probes

- Makefile
- charts/lagoon-core/Chart.yaml
- charts/lagoon-core/templates/api.deployment.yaml
- charts/lagoon-core/templates/webhooks2tasks.deployment.yaml
- charts/lagoon-core/values.yaml
Lagoon-core uses an old method for calculating the active-standby task image, rather than one that is used during the build/test phase. This PR updates the charts to support providing the image built as part of tests so we can properly use active/standby images in tests.
> update charts to use the activestandby task image overrides

- charts/lagoon-core/Chart.yaml
This release is only documentation and kubectl-build-deploy-dind related - no changes to any core services.
lagoon-core only release of https://github.com/uselagoon/lagoon/releases/tag/v2.9.1
> lagoon-core appVersion v2.9.1

- charts/lagoon-build-deploy/Chart.yaml
- charts/lagoon-build-deploy/templates/deployment.yaml
When adding the previous metrics configuration, the port was missed on adding to the deployment.
> fix: add the metrics service to the manager container

- charts/lagoon-remote/Chart.lock
- charts/lagoon-remote/Chart.yaml
Bumping remote with a patch version of lagoon-build-deploy that adds the metrics port to the remote-controller deployment
> chore: bump remote with patch lagoon-build-deploy chart version

- .github/workflows/test-suite.yaml
- Makefile
- charts/lagoon-core/Chart.yaml
- charts/lagoon-core/ci/linter-values.yaml
lagoon-core only release to match https://github.com/uselagoon/lagoon/releases/tag/v2.9.2
It also adds some reworked default settings for Harbor (using the *.invalid domain to ensure that it doesn't return), and adding additional debug steps into the github action
> update lagoon-core to v2.9.2 and introduce more actions debug

- Makefile
This is supporting code for https://github.com/uselagoon/lagoon/pull/3267
> chore: support for disabling harbor integration in core

- charts/lagoon-build-deploy/Chart.yaml
Just bumping the remote-controller version to include some additional minor fixes
> chore: bump remote-controller version

- charts/lagoon-remote/Chart.lock
- charts/lagoon-remote/Chart.yaml
> chore: bump remote-controller version in lagoon-remote

- .github/workflows/test-suite.yaml
This change reduces the timeout to 1m and runs tmate first to make it easier to catch a shell.
It also removes the old api-db checks since that was fixed in #476.
> chore: run tmate first

- charts/lagoon-core/Chart.lock
- charts/lagoon-core/Chart.yaml
- charts/lagoon-core/README.md
- charts/lagoon-core/ci/linter-values.yaml
- charts/lagoon-remote/Chart.lock
- charts/lagoon-remote/Chart.yaml
- charts/lagoon-remote/README.md
- charts/lagoon-remote/ci/linter-values.yaml
This PR updates the NATS chart dependency to pull in the new NATS v2.9.0.
> Bump NATS subchart dependency

- charts/lagoon-remote/Chart.yaml
- charts/lagoon-remote/templates/docker-host.networkpolicy.yaml
This improves the isolation of the lagoon namespace in remote clusters.
> Add networkpolicy for docker-host

- charts/lagoon-remote/Chart.yaml
- charts/lagoon-remote/templates/docker-host.networkpolicy.yaml
- charts/lagoon-remote/values.yaml
Currently the docker-host network policy is enforced with no way to disable it without removing it manually.
closes #485
> Allow docker-host network policy to be optionally disabled

- charts/lagoon-build-deploy/Chart.yaml
- charts/lagoon-build-deploy/templates/deployment.yaml
- charts/lagoon-build-deploy/values.yaml
This change supports container memory limits for containers deployed by Lagoon.
See https://github.com/uselagoon/build-deploy-tool/pull/120 for the other part of this feature.
> Container memory limit

- .github/workflows/lint-test-matrix.yaml
- .github/workflows/lint-test.yaml
- .github/workflows/test-suite.yaml
https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
> chore: use the new syntax for output variables in github actions

- .github/workflows/lint-test-matrix.yaml
- .github/workflows/lint-test.yaml
- .github/workflows/test-suite.yaml
- Makefile
This PR updates the following components in CI:
* Default Kubernetes version to 1.23 for all tests (and matrixes 1.21/1.22/1.24/1.25 for lint-test)
* Updates helm/kind-action to the latest version (and accompanying kindest image updates
* Updates gojq and kubens to latest in test-suite
* Updates ingress-nginx, MinIO and Harbor to most recent helm-charts
* Updates MariaDB, PostgreSQL to more recent compatible versions for DBaaS testing (and fixes chart values update)
> Assorted CI dependency updates

- charts/lagoon-core/Chart.yaml
- charts/lagoon-core/values.yaml
- charts/lagoon-remote/Chart.yaml
- charts/lagoon-remote/values.yaml
This is a minor update to the ssh-portal which switches JWT parsing/validation libraries to a better maintained one. See https://github.com/uselagoon/lagoon-ssh-portal/pull/126.
> Bump ssh-portal version in lagoon-remote and lagoon-core

- charts/lagoon-remote/Chart.lock
- charts/lagoon-remote/Chart.yaml
This bumps the `lagoon-build-deploy` version to the latest `v0.17.0` chart version.
> chore: bump lagoon-build-deploy version

- charts/lagoon-core/Chart.yaml
- charts/lagoon-core/values.yaml
- charts/lagoon-remote/Chart.yaml
- charts/lagoon-remote/values.yaml
No functional changes, but ssh-portal has been refactored, more test coverage, and JWT validation improvements.
> Bump ssh-portal and ssh-portal-api versions

- charts/lagoon-remote/Chart.lock
- charts/lagoon-remote/Chart.yaml
- charts/lagoon-remote/values.yaml
closes #517 
* Updated remote-calculator to v0.2.3
* Updated lagoon-build-deploy sub-chart to v0.18.0
> Lagoon-remote-updates

- charts/lagoon-core/Chart.lock
- charts/lagoon-core/Chart.yaml
- charts/lagoon-remote/Chart.lock
- charts/lagoon-remote/Chart.yaml
Updated: lagoon-build-deploy to v0.18.1 and NATS to v0.18.3 in lagoon-remote
Updated: NATS to v0.18.3 in lagoon-core
> chore: bump lagoon-build-deploy and lagoon-core

- charts/lagoon-logging/Chart.lock
- charts/lagoon-logging/Chart.yaml
Bump the logging-operator dependency to the latest version which adds support for k8s 1.25+.
> Bump logging-operator dependency

- charts/lagoon-logging/Chart.yaml
- charts/lagoon-logging/values.yaml
Closes #509 by bumping the logs-dispatcher image to a version containing a fluentd k8s plugin version which logs missing pod errors at `debug` the way the plugin used to in v2.
> Bump logs dispatcher

- charts/lagoon-core/Chart.yaml
- charts/lagoon-core/templates/_helpers.tpl
- charts/lagoon-core/templates/keycloak.secret.yaml
- charts/lagoon-core/templates/opensearch-sync.deployment.yaml
- charts/lagoon-core/templates/opensearch-sync.secret.yaml
- charts/lagoon-core/values.yaml
This PR adds [lagoon-opensearch-sync](https://github.com/uselagoon/lagoon-opensearch-sync) to the lagoon-core chart.
This new service is disabled by default, so nothing changes when upgrading an existing lagoon-core installation.
It is also disabled in CI since it has a hard requirement on an Opensearch service.
> Lagoon opensearch sync

- charts/lagoon-core/Chart.yaml
- charts/lagoon-core/ci/linter-values.yaml
- charts/lagoon-core/templates/_helpers.tpl
- charts/lagoon-core/templates/auth-server.deployment.yaml
- charts/lagoon-core/templates/auth-server.hpa.yaml
- charts/lagoon-core/templates/auth-server.service.yaml
- charts/lagoon-core/templates/ssh-token.deployment.yaml
- charts/lagoon-core/templates/ssh-token.hpa.yaml
- charts/lagoon-core/templates/ssh-token.secret.yaml
- charts/lagoon-core/templates/ssh-token.service.yaml
- charts/lagoon-core/templates/ssh-token.servicemonitor.yaml
- charts/lagoon-core/templates/ssh.deployment.yaml
- charts/lagoon-core/templates/ssh.hpa.yaml
- charts/lagoon-core/templates/ssh.service.yaml
- charts/lagoon-core/values.yaml
- charts/lagoon-remote/Chart.yaml
- charts/lagoon-remote/values.yaml
- charts/lagoon-test/Chart.yaml
- charts/lagoon-test/templates/secret.yaml
- charts/lagoon-test/values.yaml
lagoon-core:
* Add the [ssh-token](https://github.com/uselagoon/lagoon-ssh-portal#ssh-token) service. This service is disabled by default to avoid an upgrade spinning up a new load balancer on chart upgrade, but it should probably be enabled by default eventually?
* Allow disabling the ssh and auth-server services via `ssh.enabled`.
* Update ssh-portal-api to match ssh-token version.
lagoon-remote:
* Update ssh-portal version to match the other ssh services.
lagoon-test:
* Add ssh-token environment variables to test container.
> Add ssh-token service

- charts/lagoon-core/Chart.yaml
- charts/lagoon-core/values.yaml
- charts/lagoon-remote/Chart.yaml
- charts/lagoon-remote/values.yaml
Upgrade to the latest versions which fix https://github.com/uselagoon/lagoon-ssh-portal/issues/158
> Bump ssh-portal, ssh-portal-api, and ssh-token service versions

- charts/lagoon-logging/Chart.yaml
- charts/lagoon-logging/templates/logs-dispatcher.fluent-conf.configmap.yaml
This fixes a bug with the logs dispatcher where a stale DNS cache causes logs to be dropped.
> fix: handle forward target hosts with dynamic DNS

- charts/lagoon-logging/Chart.yaml
- charts/lagoon-logging/values.yaml
Bump the image used by the CDN logs collector to the latest logs-dispatcher image. I missed this when I bumped the logs-dispatcher image in a previous PR.
> Bump CDN logs collector image version

- charts/lagoon-logging/Chart.yaml
- charts/lagoon-logging/templates/logs-dispatcher.fluent-conf.configmap.yaml
This improves the speed at which the logging system adapts to DNS changes while keeping query load minimal.
> Reduce DNS cache TTL in logs-dispatcher configuration

- charts/lagoon-logs-concentrator/Chart.yaml
- charts/lagoon-logs-concentrator/README.md
- charts/lagoon-logs-concentrator/ci/linter-values.yaml
- charts/lagoon-logs-concentrator/templates/NOTES.txt
- charts/lagoon-logs-concentrator/templates/env.configmap.yaml
- charts/lagoon-logs-concentrator/templates/fluent-conf.configmap.yaml
- charts/lagoon-logs-concentrator/templates/secret.yaml
- charts/lagoon-logs-concentrator/templates/statefulset.yaml
- charts/lagoon-logs-concentrator/values.yaml
Opensearch and Elasticsearch have now diverged enough that there are separate fluentd plugins for each project.
The old fluentd Elasticsearch plugin doesn't work anymore with Opensearch v2, so this PR switches the default logs-concentrator image to a version which includes the fluentd Opensearch plugin (which supports Opensearch v2), and updates the default fluentd configuration to assume Opensearch log storage rather than Elasticsearch.
Note that this is a breaking change that requires users to update their values files.
> Switch logs-concentrator default configuration from Elasticsearch to Opensearch

- charts/lagoon-core/Chart.yaml
- charts/lagoon-core/templates/ssh-portal-api.deployment.yaml
- charts/lagoon-core/templates/ssh-token.deployment.yaml
- charts/lagoon-core/values.yaml
- charts/lagoon-remote/Chart.yaml
- charts/lagoon-remote/values.yaml
This PR bumps the ssh-portal services to v0.28.0 which, among other things, adds support for blocking Developer SSH access. See https://github.com/uselagoon/lagoon-ssh-portal/pull/172 for details.
> Bump SSH portal services

- Makefile
A minor fix to the makefile to disable HSTS headers by default in `ingress-nginx`. Needed for tests to pass in https://github.com/uselagoon/lagoon/pull/3402.
> fix: disable HSTS by default when installing ingress-nginx via makefile

- charts/lagoon-build-deploy/Chart.yaml
> chore: bump remote-controller version to v0.11.1

- charts/lagoon-core/Chart.yaml
- charts/lagoon-core/templates/_helpers.tpl
- charts/lagoon-core/templates/api-db.job.yaml
- charts/lagoon-core/templates/api.deployment.yaml
- charts/lagoon-core/templates/api.migratedb.job.yaml
- charts/lagoon-remote/Chart.lock
- charts/lagoon-remote/Chart.yaml
- charts/lagoon-test/Chart.yaml
Moves the functionality of the initContainer into a Job utilizing a chart hook.
This should the resolve the migration lock issues noted in #553.
closes #553
> Update db migration handling and lagoon-core appVersion v2.14.1

- charts/lagoon-build-deploy/Chart.yaml
Update [remote-controller to latest version 0.12.0](https://github.com/uselagoon/remote-controller/releases/tag/v0.12.0)
> chore: bump remote-controller to v0.12.0

- charts/lagoon-remote/Chart.lock
- charts/lagoon-remote/Chart.yaml
Bump the lagoon-build-deploy subchart to v0.22.0 which contains remote-controller v0.12.0.
> chore: bump lagoon-build-deploy subchart

- charts/lagoon-logging/Chart.yaml
- charts/lagoon-logging/templates/logs-dispatcher.fluent-conf.configmap.yaml
- charts/lagoon-logging/values.yaml
This feature allows injecting snippets of fluentd configuration into the
router logs processing pipeline directly before the logs are sent to the
output.
This feature is designed to allow injecting logic to manipulate or add
fields to router log records which make the log records easier to use in
Opensearch Dashboards. For example this can be used to inject a boolean
field into log records which can be used instead of a slow Opensearch
regex search.
> Add option to post process router logs

- charts/lagoon-logging/Chart.yaml
- charts/lagoon-logging/templates/logging.yaml
- charts/lagoon-logging/values.yaml
This change exposes the metrics configuration of the Logging Operator subchart and enables the fluentbit daemonset's ServiceMonitor by default.
Closes: #570
> Expose the metrics configuration of the Logging Operator subchart

- charts/lagoon-core/Chart.yaml
- charts/lagoon-core/values.yaml
This version update fixes a lot of bugs and improves compatibility with the latest versions of Opensearch.
For the full changelog see [here](https://github.com/uselagoon/lagoon-opensearch-sync/compare/v0.5.0...v0.7.0).
> Bump lagoon-opensearch-sync to v0.7.0

- charts/lagoon-build-deploy/Chart.yaml
- charts/lagoon-build-deploy/ci/linter-values.yaml
- charts/lagoon-build-deploy/templates/deployment.yaml
- charts/lagoon-build-deploy/values.yaml
- charts/lagoon-remote/values.yaml
This bumps the remote-controller to version 0.13.0 which has a number of changes. One is the ability to now inject some additional variables into builds that are prefixed with `LAGOON_CONFIG_`. These are to deprecate the existing `TASK_API/TASK_SSH` prefixed variables.
As such, this chart also needs to be updated to stage the deprecation of those variables. By default if anyone has already defined the `taskAPI/taskSSH` values, these will be consumed. But if a user chooses to do so, they can define the new values of `lagoonAPIHost`, `lagoonTokenHost/Port` and `sshPortalHost/Port` to point to the new services that will eventually replace the legacy SSH service in Lagoon.
> Bump remote-controller to version 0.13.0

- charts/lagoon-remote/Chart.lock
- charts/lagoon-remote/Chart.yaml
> chore: bump build-deploy subchart to v0.23.1

- charts/lagoon-core/Chart.yaml
- charts/lagoon-core/ci/linter-values.yaml
- charts/lagoon-core/values.yaml
Add resource requests to Lagoon Core deployments.
We have studied the actual running data for lagoon-core components for a medium-scale cluster, and are proposing a basic set of cpu resource requests.
This is a breakdown of the requested values. As this configuration of Lagoon Core requires approx 4GB RAM and 3 CPU cores to run in production, you may need to provide your own request values if you are resource constrained, or are running additional services in your cluster
See https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/#resource-units-in-kubernetes for an explanation of the mebibytes and milliCPU terms
For the services marked with an asterisk (*) as the adoption of these services rises, we may need to alter their requests accordingly
| service …
> Lagoon Core resource requests

- .github/workflows/lint-test.yaml
- .github/workflows/release.yaml
- charts/lagoon-logging/Chart.lock
- charts/lagoon-logging/Chart.yaml
- charts/lagoon-logging/templates/logging.yaml
- default.ct.yaml
This PR updates the logging operator, which is the underlying log collection system of the `lagoon-logging` chart.
Importantly, this update requires some manual CRD updates to be applied after the chart is upgraded, if upgrading from an earlier version of `lagoon-logging`:
```bash
helm repo add kube-logging https://kube-logging.github.io/helm-charts
helm show crds kube-logging/logging-operator --version 4.2.3 | kubectl apply --server-side --force-conflicts -f -
```
I'll also add the instructions above to the release notes.
> Logging operator update

- charts/lagoon-core/Chart.yaml
- charts/lagoon-core/values.yaml
- charts/lagoon-remote/Chart.yaml
- charts/lagoon-remote/values.yaml
Bump ssh-portal and associated services to the latest release `v0.30.0`.
This updates k8s API libraries for better compatibility with new versions of kubernetes, and also fixes some bugs:
* https://github.com/uselagoon/lagoon-ssh-portal/pull/197
* https://github.com/uselagoon/lagoon-ssh-portal/pull/207
* https://github.com/uselagoon/lagoon-ssh-portal/pull/240
This change also closes https://github.com/uselagoon/lagoon/issues/3431.
> Bump ssh-portal and associated services

- Makefile
This change allows `make install-lagoon-remote` to be run more than once.
Previously we would hit https://github.com/bitnami/charts/issues/15093.
The specific chart version that this PR upgrades to is the latest version of the chart which still uses MariaDB 10.11.x (the LTS minor version of v10). Later versions of the chart upgrade to MariaDB 11, which is outside the scope of this bugfix.
> fix: upgrade mariadb chart to fix upgrade bug

- charts/lagoon-build-deploy/Chart.yaml
Bumps the remote-controller version from v0.14.0 to [v0.15.0](https://github.com/uselagoon/remote-controller/releases/tag/v0.15.0)
> chore: bump remote-controller to v0.15.0

- charts/lagoon-remote/Chart.yaml
- charts/lagoon-remote/templates/_helpers.tpl
- charts/lagoon-remote/templates/ssh-core.clusterrole.yaml
- charts/lagoon-remote/templates/ssh-core.clusterrolebinding.yaml
- charts/lagoon-remote/templates/ssh-core.secret.yaml
- charts/lagoon-remote/templates/ssh-core.serviceaccount.yaml
- charts/lagoon-remote/values.yaml
In order to keep the SSH service in lagoon-core working in recent k8s clusters, a non-expiring token is needed. Since the only reason lagoon-core needs a token still is for SSH purposes, this PR creates a new set of resources with a restricted cluster role based on https://kubernetes.io/docs/tasks/configure-pod-container/configure-service-account/#manually-create-an-api-token-for-a-serviceaccount.
The role requirements differ slightly from the existing [ssh-portal role](https://github.com/uselagoon/lagoon-charts/blob/main/charts/lagoon-remote/templates/ssh-portal.clusterrole.yaml).
> feat: Add lagoon-remote-ssh-core resources

- charts/lagoon-remote/Chart.lock
- charts/lagoon-remote/Chart.yaml
Bump lagoon-build-deploy subchart to v0.25.0 to support remote-controller v0.15.0
> chore: update lagoon-build-deploy to v0.25.0

- charts/lagoon-remote/Chart.lock
- charts/lagoon-remote/Chart.yaml
> chore: bump lagoon-build-deploy subchart to v0.25.1

- charts/lagoon-logging/Chart.yaml
- charts/lagoon-logging/templates/logging.yaml
- charts/lagoon-logging/values.yaml
- charts/lagoon-logs-concentrator/Chart.yaml
- charts/lagoon-logs-concentrator/values.yaml
This PR collects a number of improvements to the logging setup in Lagoon.
it:
* updates the versions of the images used in the logs-dispatcher and logs-concentrator
* ensures that Loggin pods also schedule on infra nodes
* Allows users to configure toleration/affinity for FluentD deployments
closes #604 #589
> Logging updates

- charts/lagoon-remote/Chart.lock
- charts/lagoon-remote/Chart.yaml
> chore: update lagoon-build-deploy chart to v0.26.1

- charts/lagoon-remote/Chart.lock
- charts/lagoon-remote/Chart.yaml
> chore: update lagoon-remote with latest lagoon-build-deploy subchart

- charts/lagoon-build-deploy/Chart.yaml
- charts/lagoon-build-deploy/templates/clusterrolebinding.yaml
Just adding the missing clusterroles to the admin role to allow the lagoon namespace deployer service account to interact with builds and tasks within the namespace as required
Currently the deployer service account can interact with all other resources within the namespace during a build, and being able to interact with other builds or tasks that may exist in the namespace would be useful for being able to handle previous build or task cleanups within a build process.
> chore: add clusterroles for tasks and builds to admin and edit

- README.md
- charts/lagoon-logging/Chart.yaml
- charts/lagoon-logging/ci/linter-values.yaml
- charts/lagoon-logging/templates/cdn-logs-collector.service.yaml
- charts/lagoon-logging/templates/tests/cdn-service-annotations.yaml
- charts/lagoon-logging/values.yaml
Newer versions of the AWS load balancer controller [change the default behaviour](https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.2/guide/service/annotations/#lb-scheme) of `LoadBalancer` objects to be internal (private IP address) rather than internet-facing. The interface for making a `LoadBalancer` internet-facing is now an annotation on the k8s service object.
So this PR adds support for annotations on the CDN service, which is the only one intended to be used as a `LoadBalancer`.
> CDN service annotation support

- charts/lagoon-logging/Chart.yaml
- charts/lagoon-logging/templates/tests/cdn-service-annotations.yaml
- charts/lagoon-logging/templates/tests/test-connection.yaml
- fix: add missing helm hook annotations to test objects
- chore: bump lagoon-logging chart version
> fix lagoon logging test

- Makefile
While the fill-test-ci-values target's dependency on install-registry was correctly manipulated by the SKIP_INSTALL_REGISTRY variable, the install-lagoon-build-deploy target had a hard-coded dependency on install-registry. The result was that the registry would get installed multiple times anyway via the fill-test-ci-values target via an indirect dependency.
Fix that by removing the dependency that install-lagoon-build-deploy has on install-registry when SKIP_INSTALL_REGISTRY=true.
> fix: avoid installing the registry multiple times

- charts/lagoon-remote/Chart.yaml
- charts/lagoon-remote/ci/linter-values.yaml
- charts/lagoon-remote/templates/storage-calculator.deployment.yaml
- charts/lagoon-remote/templates/storage-calculator.service.yaml
- charts/lagoon-remote/templates/storage-calculator.servicemonitor.yaml
- charts/lagoon-remote/values.yaml
Updates storage calculator to the latest version 0.5.0 which contains metrics endpoints and additional dependency updates. Also adds support to the chart to expose the metrics.
> chore: update storage-calcluator and add metrics monitor

- charts/lagoon-core/Chart.yaml
- charts/lagoon-core/ci/linter-values.yaml
- charts/lagoon-core/templates/api.deployment.yaml
- charts/lagoon-core/templates/webhooks2tasks.deployment.yaml
- charts/lagoon-core/values.yaml
Removes the setting of the legacy registry passthrough from core due to https://github.com/uselagoon/lagoon/pull/3659
> chore: remove legacy registry passthrough from core

- charts/lagoon-core/Chart.yaml
- charts/lagoon-core/values.yaml
- charts/lagoon-remote/Chart.yaml
- charts/lagoon-remote/values.yaml
This PR updates the versions of insights-remote and insights-handler to bring them into line with the currently latest versions of the services.
> Updates insights handler and remote versions

- charts/lagoon-core/ci/linter-values.yaml
- charts/lagoon-core/templates/api.deployment.yaml
- charts/lagoon-core/templates/keycloak.deployment.yaml
- charts/lagoon-remote/Chart.yaml
This PR adds the keycloak migrations to the initcontainer run in the API
https://github.com/uselagoon/lagoon/pull/3612
> Support Keycloak migrations via the API init-container

- Makefile
- charts/lagoon-core/Chart.yaml
- charts/lagoon-core/ci/linter-values.yaml
- charts/lagoon-core/templates/api-db.statefulset.yaml
- charts/lagoon-core/templates/keycloak-db.statefulset.yaml
- charts/lagoon-core/values.yaml
There are some changes to all the probe types for both apiDB and keycloakDB to fix unnecessary warnings in logs and to prevent premature connections.
The [init script](https://github.com/uselagoon/lagoon-images/blob/main/images/mariadb/entrypoints/9999-mariadb-init.bash) from the `uselagoon/mariadb` base image starts `mysqld` multiple times to install/upgrade the schema, so a TCP probe will signal startup is complete before the init is actually done. The probe is changed to check for a file that signifies init completions. Depends on https://github.com/uselagoon/lagoon-images/pull/957.
`[Warning] Access denied for user 'root'@'127.0.0.1' (using password: YES)`
Using `localhost` and port `3306` forces mysqladmin to connect to `127.0.0.1` via TCP, instead of via socket. The …
> feat: apiDB/keycloakDB startup/readiness/liveness probes and startup/shutdown time

- charts/lagoon-core/Chart.yaml
- charts/lagoon-core/values.yaml
- charts/lagoon-test/Chart.yaml
Corresponding charts release for https://github.com/uselagoon/lagoon/releases/tag/v2.18.1
> update Lagoon appVersion to v2.18.1

- charts/lagoon-core/Chart.yaml
- charts/lagoon-core/ci/linter-values.yaml
- charts/lagoon-core/templates/api.deployment.yaml
- charts/lagoon-core/values.yaml
- charts/lagoon-remote/Chart.yaml
- charts/lagoon-remote/values.yaml
- charts/lagoon-test/Chart.yaml
This PR updates Lagoon to appVersion v2.18.2
It also updates storage-calculator to v0.5.3
It also adds the logic to API.deployment to present the ssh endpoints for https://github.com/uselagoon/lagoon/pull/3632
> update Lagoon appVersion to v2.18.2

- charts/lagoon-logs-concentrator/Chart.yaml
- charts/lagoon-logs-concentrator/templates/metrics-service.yaml
- charts/lagoon-logs-concentrator/templates/service.yaml
- charts/lagoon-logs-concentrator/templates/servicemonitor.yaml
- charts/lagoon-logs-concentrator/templates/statefulset.yaml
- charts/lagoon-logs-concentrator/values.yaml
When the main service is used as a load balancer service to allow public
access through mTLS, the metrics should not be exposed on the same
service.
> chore: Use dedicated service for metrics

- charts/lagoon-core/Chart.yaml
- charts/lagoon-core/values.yaml
- chore: bump lagoon-opensearch-sync to v0.8.0
- chore: bump lagoon-core chart version
> bump opensearch sync

- charts/lagoon-core/Chart.yaml
- charts/lagoon-core/values.yaml
- charts/lagoon-remote/Chart.yaml
- charts/lagoon-remote/values.yaml
Note that this version of ssh-portal-api depends on https://github.com/uselagoon/lagoon/pull/3721 (which is why CI currently fails).
> bump ssh portal

- .github/workflows/test-suite.yaml
- charts/lagoon-core/Chart.yaml
- charts/lagoon-core/values.yaml
- charts/lagoon-remote/Chart.yaml
- charts/lagoon-remote/values.yaml
- charts/lagoon-test/Chart.yaml
Accompanying release for https://github.com/uselagoon/lagoon/releases/tag/v2.19.0
> Lagoon v2.19.0 release

- charts/lagoon-docker-host/Chart.yaml
- charts/lagoon-docker-host/README.md
- charts/lagoon-remote/Chart.lock
- charts/lagoon-remote/Chart.yaml
- charts/lagoon-remote/values.yaml
This PR updates the version of the docker-host image to v3.5.0 - which contains the update to v26 of docker.
And also closes #636
> chore: update docker-host to v3.5.0 and build-deploy to 0.27.0

- charts/lagoon-build-deploy/Chart.yaml
- charts/lagoon-build-deploy/crds/crd.lagoon.sh_lagoonbuilds.yaml
- charts/lagoon-build-deploy/crds/crd.lagoon.sh_lagoontasks.yaml
Updates crds to include the organization fields in the spec
> chore: update crd for builds and tasks

- charts/lagoon-remote/Chart.lock
- charts/lagoon-remote/Chart.yaml
Update lagoon-remote with latest build-deploy chart version with crd changes
> chore: update build-deploy version in lagoon-remote

- Makefile
- charts/lagoon-build-deploy/Chart.yaml
- charts/lagoon-core/Chart.yaml
- charts/lagoon-core/ci/linter-values.yaml
- charts/lagoon-core/ci/testlagoon-main-override.yaml
- charts/lagoon-core/templates/api.deployment.yaml
- charts/lagoon-core/templates/webhooks2tasks.deployment.yaml
- charts/lagoon-core/values.yaml
- charts/lagoon-remote/Chart.yaml
This PR adds support for the api sidecar added in https://github.com/uselagoon/lagoon/pull/3662
> feat: add api-sidecar internal handler

- charts/lagoon-remote/Chart.yaml
- charts/lagoon-remote/templates/ssh-core.clusterrole.yaml
In [Lagoon 2.20.0](https://github.com/uselagoon/lagoon/releases/tag/v2.20.0), the `kubectl` binary was upgraded, and it appears to use a different method of scaling deployments that requires an extra permission. This PR adds the ability for the lagoon-remote ssh-core service account to `patch`, in addition to `get` and `update`.
> fix: lagoon-remote-ssh-core scale permissions

- charts/lagoon-logging/Chart.lock
- charts/lagoon-logging/Chart.yaml
- charts/lagoon-logging/templates/logging.yaml
- charts/lagoon-logging/values.yaml
- charts/lagoon-logs-concentrator/Chart.yaml
- charts/lagoon-logs-concentrator/values.yaml
Currently, this PR updates the charts to 4.9.1 which includes https://github.com/kube-logging/logging-operator/pull/1794
> Update lagoon-logging chart, logs-concentrator and logs-dispatcher images

- charts/lagoon-core/templates/api.deployment.yaml
This adds the same `KEYCLOAK_FRONTEND_URL` variable that is used by keycloak itself to set the frontend, to inject into the API to be used in the `.well-known` discovery endpoint.
This adds the `/auth` path to this URL so that tools will be able to auto detect the correct path that keycloak is configured with correctly.
If in the future this `/auth` path is removed from being [hardcoded](https://github.com/uselagoon/lagoon/blob/main/services/keycloak/entrypoints/default-keycloak-entrypoint.sh#L10) as a path, tools will be able to rediscover keycloak without the relative path to `/auth`
> change: set keycloak_frontend_url for external keycloak

- .github/workflows/lint-test.yaml
- .github/workflows/release.yaml
- default.ct.yaml
We don't appear to use `banzaicloud-stable` anymore for anything, and they are currently experiencing DNS issues that are causing tests to fail. The crds referenced in `lagoon-logging` are installed by kube-logging operator now.
The README in the `lagoon-logging` chart probably needs updating. This just removes banzaicloud-stable from the actions to allow tests to pass.
> chore: remove unused banzaicloud-stable repo

- charts/lagoon-core/Chart.lock
- charts/lagoon-core/Chart.yaml
- charts/lagoon-core/ci/linter-values.yaml
- charts/lagoon-core/templates/_helpers.tpl
- charts/lagoon-core/templates/nats-concentrator.service.yaml
- charts/lagoon-core/templates/nats.secret.yaml
- charts/lagoon-core/templates/ssh-portal-api.deployment.yaml
- charts/lagoon-core/values.yaml
- charts/lagoon-remote/Chart.lock
- charts/lagoon-remote/Chart.yaml
- charts/lagoon-remote/ci/linter-values.yaml
- charts/lagoon-remote/templates/_helpers.tpl
- charts/lagoon-remote/templates/nats.secret.yaml
- charts/lagoon-remote/templates/ssh-portal.deployment.yaml
- charts/lagoon-remote/values.yaml
This PR upgrades the NATS subchart dependency to 1.0.
This is a __breaking change__. The NATS chart has completely restructured its configuration between v0.x and v1.x.
So by necessity the NATS subchart configuration of `lagoon-core` and `lagoon-remote` also had to be restructured.
In general, the major upstream change affecting the Lagoon charts is that `nats.*` values have mostly been moved to `nats.config.*`.
In particular, the following values required by the Lagoon charts have changed:
Lagoon Core:
| Old path                                 | New path                              |
| ---                                      | ---                                   |
| `nats.cluster.name`                      | `nats.config.cluster.name`            |
| …
> Upgrade nats subchart to v1.2

- charts/lagoon-core/Chart.yaml
- charts/lagoon-core/templates/keycloak.secret.yaml
- charts/lagoon-core/templates/ui.deployment.yaml
- charts/lagoon-core/values.yaml
Support for https://github.com/uselagoon/lagoon/pull/3803
CI will fail because no chart version bumps done, this is intended to be merged into #694  in preparation for a release.
> chore: add support for lagoon-ui-oidc client values

- .github/workflows/test-suite.yaml
- charts/lagoon-build-deploy/Chart.yaml
- charts/lagoon-build-deploy/README.md
- charts/lagoon-build-deploy/crds/crd.lagoon.sh_lagoonbuilds.yaml
- charts/lagoon-build-deploy/crds/crd.lagoon.sh_lagoontasks.yaml
Updates the remote-controller to v0.20.0 which introduces the v1beta2 API, deprecating the v1beta1 API.
v1beta1 builds will still be processed and actioned, but once completed the CR will be deleted, which paves the way for the removal of the v1beta1 API in a future release.
Installing this version of the `lagoon-build-deploy` chart will require the CRD to be updated, the chart README has been updated to include some instructions on how to do this.
> feat: add v1beta2 crd and update remote-controller verison

- charts/lagoon-build-deploy/Chart.yaml
fixes error:
```
error preparing package: error enriching package from annotations: 1 error occurred:
* invalid annotation: invalid crds value
(package: lagoon-build-deploy version: 0.30.0)
```
> chore: republish with updated artifacthub crds

- charts/lagoon-build-deploy/Chart.yaml
> chore: update remote-controller to v0.20.3

- charts/lagoon-remote/Chart.lock
- charts/lagoon-remote/Chart.yaml
> chore: update lagoon-build-deploy to v0.30.3

- .github/workflows/lint-test.yaml
- .github/workflows/release.yaml
- default.ct.yaml
Currently our process to skirt the chart increment requirement is to create a feature branch in this repository (eg #694), then make changes to other repositories (eg https://github.com/uselagoon/lagoon/pull/3826). Once this feature branch is merged, we have to revert the changes in other repositories (eg https://github.com/uselagoon/lagoon/pull/3842). This is quite frustrating, and has lead to issues after a release when tests start failing because of some reference that wasn't reverted, or was reverted incorrectly. All could have been avoided if we just continued merging to main and released the chart when we were ready to do so.
The govuk team have described similar frustrations with this enforcement [here](https://github.com/alphagov/govuk-helm-charts/commit/cfa1a475b52a672d976bb56c0ff …
> chore: ignore chart version bump, dont publish charts if tag exists

- charts/lagoon-core/Chart.yaml
- charts/lagoon-core/templates/api.deployment.yaml
- charts/lagoon-core/templates/keycloak.secret.yaml
- charts/lagoon-core/values.yaml
Support for https://github.com/uselagoon/lagoon/pull/3841
> chore: add support for keycloak admin api client values

- charts/lagoon-remote/Chart.lock
- charts/lagoon-remote/Chart.yaml
Updates the dbaas-operator chart dependency to v0.3.1 which includes the replacement kube-rbac-proxy image https://github.com/amazeeio/charts/pull/57
> chore: update dbaas-operator chart version

- charts/lagoon-build-deploy/Chart.yaml
- charts/lagoon-build-deploy/templates/deployment.yaml
- charts/lagoon-build-deploy/templates/service.yaml
- charts/lagoon-build-deploy/templates/servicemonitor.yaml
- charts/lagoon-build-deploy/values.yaml
Updates the `lagoon-build-deploy` chart to support the removal of the kube-rbac-proxy from the remote-controller https://github.com/uselagoon/remote-controller/pull/272
> chore: remove kube-rbac-proxy from lagoon-build-deploy

- charts/lagoon-remote/Chart.yaml
- charts/lagoon-remote/templates/_helpers.tpl
- charts/lagoon-remote/templates/sysctl-configure.clusterrole.yaml
- charts/lagoon-remote/templates/sysctl-configure.clusterrolebinding.yaml
- charts/lagoon-remote/templates/sysctl-configure.daemonset.yaml
- charts/lagoon-remote/templates/sysctl-configure.serviceaccount.yaml
- charts/lagoon-remote/values.yaml
To remove https://github.com/uselagoon/build-deploy-tool/blob/d2508efa74871cabe4c477e44bbe87e339d99f5d/internal/servicetypes/opensearch.go#L75-L96 from the opensearch and elasticsearch templates so that no containers require the `privileged: true` value. There needs to be some option to configure any sysctl values as required in `lagoon-remote`.
This adds a `DaemonSet` that allows for setting this value, and potentially other values. This is disabled by default.
Ideally the underlying instances that run kubernetes should have the values updated to remove the need for this, but in cases where it isn't possible to do so, this `DaemonSet` provides the capability.
Linked to https://github.com/uselagoon/build-deploy-tool/pull/395
> feat: add sysctl configure daemonset

- charts/lagoon-remote/Chart.yaml
- charts/lagoon-remote/templates/storage-calculator.clusterrolebinding.yaml
- charts/lagoon-remote/templates/storage-calculator.deployment.yaml
- charts/lagoon-remote/templates/storage-calculator.role.yaml
- charts/lagoon-remote/templates/storage-calculator.service.yaml
- charts/lagoon-remote/templates/storage-calculator.servicemonitor.yaml
- charts/lagoon-remote/values.yaml
Update to use metrics endpoint fixes in https://github.com/uselagoon/storage-calculator/pull/18
> chore: update storage-calculator and adjust metrics endpoint

- .github/workflows/test-suite.yaml
- Makefile
Supporting changes for https://github.com/uselagoon/lagoon/pull/3829
> refactor: install isolated lagoon for upgradeability

- charts/lagoon-build-deploy/Chart.yaml
- charts/lagoon-build-deploy/templates/servicemonitor.yaml
After #704 was introduced, the `ServiceMonitor` wasn't updated to include the required fields for authentication. This updates the `ServiceMonitor` with the required changes for authentication.
> fix: lagoon-build-deploy servicemonitor for new metrics endpoint

- Makefile
- charts/lagoon-core/Chart.yaml
- charts/lagoon-core/templates/api-db.statefulset.yaml
- charts/lagoon-core/templates/keycloak-db.statefulset.yaml
- charts/lagoon-core/templates/keycloak.deployment.yaml
- charts/lagoon-core/values.yaml
Support for https://github.com/uselagoon/lagoon/pull/3816
> chore: support db vendor change

- .gitignore
- Makefile
- charts/lagoon-core/Chart.yaml
- charts/lagoon-core/ci/linter-values.yaml
- charts/lagoon-core/templates/ssh-portal-api.deployment.yaml
- charts/lagoon-core/templates/ssh-token.deployment.yaml
- charts/lagoon-core/values.yaml
Supporting changes for https://github.com/uselagoon/lagoon/pull/3860
> chore: support for keycloak 26

- charts/lagoon-build-deploy/Chart.yaml
- charts/lagoon-build-deploy/crds/crd.lagoon.sh_lagoonbuilds.yaml
- charts/lagoon-build-deploy/crds/crd.lagoon.sh_lagoontasks.yaml
This just restores the deprecated v1beta1 CRD version in an unserved state to preserve upgrade paths for older installations.
> chore: re-add deprecated v1beta1 build and task crd unserved

- charts/lagoon-remote/Chart.yaml
- charts/lagoon-remote/values.yaml
Bump versions of
* storage-calculator 0.7.0 -> 0.8.0
* insights-remote 0.0.11 -> 0.0.12
> chore: update storage-calc and insights-remote versions

- charts/lagoon-remote/Chart.yaml
- charts/lagoon-remote/templates/storage-calculator.clusterrole.yaml
After the secret changes were added to storage calculator, the role wasn't updated to reflect the requests to get the secret. This fixes the role so that the calculator can retrieve secrets.
> fix: storage-calculator cluster role

- Makefile
While testing something with k8up in a local-stack, the backup-handler image fails to pull if checked out in a working branch. This fixes it so that it correctly uses the built and pushed image if not using a stable local-stack.
> chore: fix missing backup-handler image override

- charts/lagoon-logs-concentrator/Chart.yaml
- charts/lagoon-logs-concentrator/templates/fluent-conf.configmap.yaml
The reload_* options tell fluentd to ask the Opensearch Nodes API for
endpoint IP addresses to add to the round-robin pool for outbound
connections. This behaviour is never correct in our configuration
because we use TLS, and the certificate only has the configured
hostname, not the pod IPs.
So this change configures fluentd to only use the configured hostname.
> fix: only use the configured hostname for opensearch output

- Makefile
Add make variables to enable or disable certain notifications, also enables slack by default
> chore: support logs2notifications options

- Makefile
Just a simple one that uses the the token created by the ssh core feature being enabled to be used instead of creating a short lived token.
> chore: use the lagoon-remote ssh-core token in tests

- charts/lagoon-remote/Chart.yaml
- charts/lagoon-remote/templates/docker-host.service.yaml
To make selecting from the individual docker hosts with their direct services, this adds a dedicated label to be able to select only the direct services in the cluster.
> chore: add dedicated label to docker-host services

- charts/lagoon-build-deploy/Chart.yaml
- charts/lagoon-build-deploy/templates/deployment.yaml
- charts/lagoon-build-deploy/templates/secret.yaml
Moves the harbor username and password into the secret to match rabbitmq credentials
> chore: move harbor credential into secret

- charts/lagoon-build-deploy/Chart.yaml
Update `remote-controller` to v0.23.0 and release the chart.
> chore: update remote-controller to v0.23.0

- charts/lagoon-logs-concentrator/Chart.yaml
- charts/lagoon-logs-concentrator/templates/statefulset.yaml
- charts/lagoon-logs-concentrator/values.yaml
With a full buffer the logs concentrator can take longer to start up
than the default liveness probe. Making the probes configurable allows
operators to adjust them as required according to the size of the
environment.
> Add startup probe and allow configuration of probes

- charts/lagoon-core/Chart.yaml
- charts/lagoon-logging/Chart.yaml
- charts/lagoon-remote/Chart.yaml
- charts/lagoon-test/Chart.yaml
lagoon charts release for Lagoon Core 2.25.0
> update versions for lagoon release v2.25.0

- charts/lagoon-remote/Chart.yaml
- charts/lagoon-remote/templates/insights-remote.deployment.yaml
Fixes the variable used for insights-remote to enable broker TLS (https://github.com/uselagoon/insights-remote/blob/v0.0.13/cmd/main.go#L229)
> fix: use correct variable for broker tls in insights-remote

- Makefile
Enable email notifications in development, and fix the port setting used for the logs2notifcation email service.
This is to support https://github.com/uselagoon/lagoon/pull/3920 in local development
> chore: enable email notifications in development

- charts/lagoon-core/Chart.yaml
- charts/lagoon-core/values.yaml
- charts/lagoon-remote/Chart.lock
- charts/lagoon-remote/Chart.yaml
- charts/lagoon-test/Chart.yaml
lagoon charts release for Lagoon Core 2.26.0
> Updates to core, remote, and test to lagoon 2.26.0

- charts/lagoon-core/Chart.yaml
- charts/lagoon-core/values.yaml
Update `lagoon-core` to v2.26.1. This includes a bump to the `lagoon-ui` to the same version.
Excluded from this are changes to the `build-deploy-image` as there have been no changes to this image in this patch release. This keeps the `build-deploy-image` locked to v2.26.0
Will need to merge docs afterwards https://github.com/uselagoon/lagoon/pull/3936
> chore: update lagoon-core to v2.26.1

- Makefile
- charts/lagoon-core/Chart.yaml
- charts/lagoon-core/templates/actions-handler.deployment.yaml
Support for https://github.com/uselagoon/lagoon/pull/3709 and https://github.com/uselagoon/remote-controller/pull/267
> feat: support for retention policies

- Makefile
- charts/lagoon-core/Chart.yaml
- charts/lagoon-core/templates/actions-handler.deployment.yaml
Fixes missing injection of `S3_FILES_ACCESS_KEY_ID` and `S3_FILES_SECRET_ACCESS_KEY` needed by the actions-handler as part of https://github.com/uselagoon/lagoon/pull/3709
> fix: actions-handler template retention policy s3 variables

- Makefile
- charts/lagoon-core/Chart.yaml
- charts/lagoon-core/ci/linter-values.yaml
- charts/lagoon-core/templates/keycloak.deployment.yaml
- charts/lagoon-core/templates/keycloak.service.yaml
- charts/lagoon-core/templates/keycloak.servicemonitor.yaml
- charts/lagoon-core/values.yaml
- ci/grafana-dashboards/keycloak-capacity.yaml
- ci/grafana-dashboards/keycloak-troubleshoot.yaml
- ci/grafana-dashboards/ssh-portal.yaml
This adds support for keycloak metrics to be exposed with a servicemonitor
Optionally installs prometheus and grafana in the local stack for local verification, with some basic grafana dashboards for [keycloak](https://github.com/keycloak/keycloak-grafana-dashboard) and the ssh-portal
Linked https://github.com/uselagoon/lagoon/pull/3947
> feat: keycloak metrics

- charts/lagoon-build-deploy/Chart.yaml
- charts/lagoon-build-deploy/templates/deployment.yaml
- charts/lagoon-docker-host/Chart.yaml
- charts/lagoon-docker-host/templates/docker-host.statefulset.yaml
- charts/lagoon-remote/Chart.yaml
- charts/lagoon-remote/templates/docker-host.statefulset.yaml
- charts/lagoon-remote/templates/insights-remote.deployment.yaml
- charts/lagoon-remote/templates/storage-calculator.deployment.yaml
Adds support of `valueFrom` field when adding environment variables in a container by passing `extraEnvs` to environment variables directly from values.
Related issue: https://amazeeio.atlassian.net/browse/PLAT-571
> Pass extraEnvs to environment variables directly from values

- Makefile
- ci/grafana-dashboards/aergia.yaml
Support to optionally install aergia along side lagoon for local testing/verification of aergia functionality. It is disabled in charts-testing.
Associated PR that utilises this functionality https://github.com/uselagoon/lagoon/pull/3949
> test: optionally install aergia for local development

- charts/lagoon-remote/Chart.lock
- charts/lagoon-remote/Chart.yaml
Update the lagoon-build-deploy subchart version to v0.36.0
> chore: update lagoon-build-deploy subchart to v0.36.0

- charts/lagoon-core/Chart.yaml
- charts/lagoon-core/values.yaml
- charts/lagoon-remote/Chart.yaml
This bumps the lagoon-core and lagoon-remote chart versions as part of the v2.27.0 release.
> chore: bump chart versions for lagoon v2.27.0 release

- charts/lagoon-logging/Chart.yaml
- charts/lagoon-logging/templates/cdn-logs-collector-metrics.service.yaml
This only creates the service for metrics of the CDN logs collector component, introduced in #791, when the component itself is enabled.
> Only expose metrics for enabled CDN logs collector

- charts/lagoon-logging/Chart.yaml
- charts/lagoon-logging/templates/logging.yaml
- charts/lagoon-logging/values.yaml
In some setups it can be required to use an alternative container image
registry than those used by the operator.
> Make logging-operator images configurable

- Makefile
Necessary for https://github.com/uselagoon/lagoon/pull/3970
This PR allows the insights-handler to be enabled in the local-stack. 
It also supports a custom insights-handler image through the `INSIGHTS_HANDLER_IMAGE_REPO` and `INSIGHTS_HANDLER_IMAGE_TAG` variables.
> feat: allow enabling of insights handler on local stack

- Makefile
By default, the local-stack installs k8upv1alpha1 ("v1"), but this does not support ARM systems. This makes it impossible to build the local-stack directly with backups enabled using `make k3d/local-stack INSTALL_K8UP=true` without manually removing the offending make target dependency.
This PR changes the installation so that v1 is only installed if explicitly enabled via the `REMOTE_CONTROLLER_K8UP_VERSION` variable.
> fix: local-stack installation of k8up on ARM systems

- charts/lagoon-core/Chart.yaml
- charts/lagoon-core/files/seed-core.js
The existing script does not wait for Keycloak to start and be ready, which leads to scenarios where keycloak returns a 503, and the user never gets created.
This was happening to me on my lagoon cluster on my homeserver.
This PR fixes it by waiting until keycloak returns `200` on the `/auth/admin/realm/master` path.
> fix: seeding not waiting for keycloak before creating user

- .github/workflows/test-suite.yaml
- Makefile
Since Bitnami changed all their stuff around, it has the potential for flow on issues for our charts and local testing. This removes all bitnami references and uses some charts that are relatively new that are mostly drop in replacements, but the key difference is they use upstream images from the providers, rather than bitnami images.
Cloudpirates.io has made charts available basically as bitnami alternatives, see their blog post https://www.cloudpirates.io/knowledge/blog/unsere-open-source-helm-charts-als-bitnami-alternative
As these charts are only used for CI/local development purposes, this is more than suitable for now.
Bonus, it looks like this allows mongodb to be used on ARM systems now as the [upstream mongo](https://hub.docker.com/_/mongo) image appears to provide this.
> chore: remove bitnami charts

- charts/lagoon-core/Chart.yaml
- charts/lagoon-core/files/seed-core.js
- charts/lagoon-core/templates/api.seeding.job.yaml
Just some small adjustments to the seed user/org job. 
First is to set the organization name to be made "safe" and lowercase. While setting the full value as the friendly name.
Second adjusts the keycloak url to use the internal one if frontendurl is not provided, and prefer to use the internal lagoon api endpoint
> fix: seeding job api references and organization name setup
