uselagoon/lagoon-charts

charts/lagoon-logging/Chart.yaml, charts/lagoon-logging/ci/linter-values.yaml, charts/lagoon-logging/templates/logs-dispatcher.fluent-conf.configmap.yaml, charts/lagoon-logging/values.yaml
This PR consolidates log indices coming from internal cluster services.
Closes: #7
=> Consolidate service indices

charts/lagoon-core/Chart.yaml, charts/lagoon-core/ci/linter-values.yaml, charts/lagoon-core/templates/_helpers.tpl, charts/lagoon-core/templates/api.secret.yaml, charts/lagoon-core/templates/auth-server.deployment.yaml, charts/lagoon-core/templates/auth-server.service.yaml, charts/lagoon-core/templates/broker.secret.yaml, charts/lagoon-core/templates/broker.statefulset.yaml, charts/lagoon-core/templates/webhook-handler.deployment.yaml, charts/lagoon-core/templates/webhook-handler.ingress.yaml, charts/lagoon-core/templates/webhook-handler.service.yaml, charts/lagoon-core/templates/webhooks2tasks.deployment.yaml, charts/lagoon-core/values.yaml, ct.yaml
New components include:
* auth-server
* webhook-handler
* webhooks2tasks
Closes: amazeeio/lagoon#2012
Closes: amazeeio/lagoon#2030
=> Add some more lagoon-core components

charts/lagoon-ssh/Chart.yaml, charts/lagoon-ssh/templates/ssh.deployment.yaml, charts/lagoon-ssh/templates/ssh.secret.yaml
This facilitates use as a subchart.
=> Convert some lagoon-ssh values to templates

charts/lagoon-core/Chart.yaml, charts/lagoon-core/ci/linter-values.yaml, charts/lagoon-logging/Chart.yaml, charts/lagoon-logging/ci/linter-values.yaml
=> Comment fixes

charts/lagoon-core/Chart.yaml, charts/lagoon-core/README.md, charts/lagoon-core/ci/linter-values.yaml, charts/lagoon-core/templates/_helpers.tpl, charts/lagoon-core/templates/keycloak.ingress.yaml, charts/lagoon-core/templates/ui.deployment.yaml, charts/lagoon-core/templates/ui.ingress.yaml, charts/lagoon-core/templates/ui.service.yaml, charts/lagoon-core/values.yaml
This also makes some supporting changes such as adding an ingress for keycloak.
=> Add Lagoon UI to lagoon-core chart

charts/lagoon-core/Chart.yaml, charts/lagoon-core/ci/linter-values.yaml, charts/lagoon-core/templates/_helpers.tpl, charts/lagoon-core/templates/auto-idler.deployment.yaml, charts/lagoon-core/templates/backup-handler.deployment.yaml, charts/lagoon-core/templates/storage-calculator.deployment.yaml, charts/lagoon-core/values.yaml
This PR also adds some fixes for auto-idler.
=> Add storage-calculator to lagoon-core chart

charts/lagoon-core/Chart.lock, charts/lagoon-core/Chart.yaml, charts/lagoon-core/README.md, charts/lagoon-core/ci/linter-values.yaml, charts/lagoon-core/templates/_helpers.tpl, charts/lagoon-core/templates/backup-handler.deployment.yaml, charts/lagoon-core/templates/ssh.deployment.yaml, charts/lagoon-core/templates/ssh.service.yaml, charts/lagoon-core/values.yaml
=> Integrate ssh service into lagoon-core chart

charts/lagoon-core/Chart.yaml, charts/lagoon-core/README.md, charts/lagoon-core/templates/auto-idler.deployment.yaml, charts/lagoon-core/templates/drush-alias.deployment.yaml, charts/lagoon-core/templates/drush-alias.ingress.yaml, charts/lagoon-core/templates/drush-alias.service.yaml, charts/lagoon-core/templates/logs-db-curator.deployment.yaml, charts/lagoon-core/templates/logs2email.deployment.yaml, charts/lagoon-core/templates/logs2microsoftteams.deployment.yaml, charts/lagoon-core/templates/logs2rocketchat.deployment.yaml, charts/lagoon-core/templates/logs2slack.deployment.yaml, charts/lagoon-core/templates/storage-calculator.deployment.yaml, charts/lagoon-core/templates/webhook-handler.deployment.yaml, charts/lagoon-core/templates/webhook-handler.ingress.yaml, charts/lagoon-core/templates/webhook-handler.service.yaml, charts/lagoon-core/templates/webhooks2tasks.deployment.yaml, charts/lagoon-core/values.yaml
=> Add ability to enable/disable auxiliary services in lagoon-core

charts/lagoon-remote/Chart.yaml, charts/lagoon-remote/README.md
=> Lagoon remote README

charts/lagoon-core/Chart.yaml, charts/lagoon-core/templates/api-db.statefulset.yaml, charts/lagoon-core/templates/broker.statefulset.yaml, charts/lagoon-core/templates/keycloak-db.statefulset.yaml
=> Use a global imagePullSecret in all lagoon-core templates

charts/lagoon-core/Chart.yaml, charts/lagoon-core/templates/api-db.statefulset.yaml, charts/lagoon-core/templates/api-redis.deployment.yaml, charts/lagoon-core/templates/api.deployment.yaml, charts/lagoon-core/templates/auth-server.deployment.yaml, charts/lagoon-core/templates/auto-idler.deployment.yaml, charts/lagoon-core/templates/backup-handler.deployment.yaml, charts/lagoon-core/templates/broker.statefulset.yaml, charts/lagoon-core/templates/drush-alias.deployment.yaml, charts/lagoon-core/templates/keycloak-db.statefulset.yaml, charts/lagoon-core/templates/keycloak.deployment.yaml, charts/lagoon-core/templates/logs-db-curator.deployment.yaml, charts/lagoon-core/templates/logs2email.deployment.yaml, charts/lagoon-core/templates/logs2microsoftteams.deployment.yaml, charts/lagoon-core/templates/logs2rocketchat.deployment.yaml, charts/lagoon-core/templates/logs2slack.deployment.yaml, charts/lagoon-core/templates/ssh-portal.deployment.yaml, charts/lagoon-core/templates/ssh.deployment.yaml, charts/lagoon-core/templates/storage-calculator.deployment.yaml, charts/lagoon-core/templates/ui.deployment.yaml, charts/lagoon-core/templates/webhook-handler.deployment.yaml, charts/lagoon-core/templates/webhooks2tasks.deployment.yaml, charts/lagoon-core/values.yaml
OpenShift compatibility is not an aim for this PR.
Closes: #30
=> Add non-root podsecuritycontext

charts/lagoon-core/Chart.yaml, charts/lagoon-core/templates/api.hpa.yaml, charts/lagoon-core/templates/auth-server.hpa.yaml, charts/lagoon-core/templates/backup-handler.hpa.yaml, charts/lagoon-core/templates/broker.hpa.yaml, charts/lagoon-core/templates/drush-alias.hpa.yaml, charts/lagoon-core/templates/logs2email.hpa.yaml, charts/lagoon-core/templates/logs2microsoftteams.hpa.yaml, charts/lagoon-core/templates/logs2rocketchat.hpa.yaml, charts/lagoon-core/templates/logs2slack.hpa.yaml, charts/lagoon-core/templates/ssh-portal.hpa.yaml, charts/lagoon-core/templates/ssh.hpa.yaml, charts/lagoon-core/templates/ui.hpa.yaml, charts/lagoon-core/templates/webhook-handler.hpa.yaml, charts/lagoon-core/templates/webhooks2tasks.hpa.yaml
=> Add optional HPAs for all scalable services

charts/lagoon-core/Chart.yaml, charts/lagoon-core/ci/linter-values.yaml, charts/lagoon-core/templates/_helpers.tpl, charts/lagoon-core/templates/api.deployment.yaml, charts/lagoon-core/templates/broker.statefulset.yaml, charts/lagoon-core/templates/controllerhandler.deployment.yaml, charts/lagoon-core/templates/logs2email.deployment.yaml, charts/lagoon-core/templates/logs2microsoftteams.deployment.yaml, charts/lagoon-core/templates/logs2rocketchat.deployment.yaml, charts/lagoon-core/templates/logs2slack.deployment.yaml, charts/lagoon-core/templates/webhook-handler.deployment.yaml, charts/lagoon-core/templates/webhooks2tasks.deployment.yaml, charts/lagoon-core/values.yaml
* Bump app version
* Unpin several image tags in CI - we can rely on the app version now
* Set several more environment variables used by various services. Closes: #72 
* Add controllerhandler service to lagoon-core. Closes: #70
=> Lagoon 1.9.0 updates

charts/lagoon-core/Chart.yaml, charts/lagoon-core/templates/api.deployment.yaml, charts/lagoon-core/templates/controllerhandler.deployment.yaml, charts/lagoon-core/templates/logs2email.deployment.yaml, charts/lagoon-core/templates/logs2slack.deployment.yaml, charts/lagoon-core/templates/webhooks2tasks.deployment.yaml
=> Set API_HOST to the full API URL

charts/lagoon-core/Chart.lock, charts/lagoon-core/Chart.yaml, charts/lagoon-core/README.md, charts/lagoon-core/values.yaml, ct.yaml
=> Remove harbor dependency from lagoon-core

charts/lagoon-remote/Chart.yaml, charts/lagoon-remote/templates/docker-host.deployment.yaml, charts/lagoon-remote/values.yaml
=> coalesce docker-host image tag in lagoon-remote

charts/lagoon-core/templates/api-redis.deployment.yaml
=> coalesce apiredis image tag

charts/lagoon-core/templates/api.deployment.yaml, charts/lagoon-core/templates/controllerhandler.deployment.yaml, charts/lagoon-core/templates/webhooks2tasks.deployment.yaml, charts/lagoon-core/values.yaml
I don't think this is really needed and a leftover from old OpenShift times
=> remove registry

charts/lagoon-core/templates/api.deployment.yaml, charts/lagoon-core/templates/api.secret.yaml, charts/lagoon-core/values.yaml
necessary changes for https://github.com/amazeeio/lagoon/pull/2218
=> rename s3 credential variables to s3Files

charts/lagoon-core/Chart.yaml, charts/lagoon-core/ci/linter-values.yaml, charts/lagoon-core/templates/api.deployment.yaml, charts/lagoon-core/templates/controllerhandler.deployment.yaml, charts/lagoon-core/templates/webhooks2tasks.deployment.yaml, charts/lagoon-core/values.yaml
=> Fix env vars

.github/workflows/lint-test.yaml, README.md, charts/lagoon-test/.helmignore, charts/lagoon-test/Chart.yaml, charts/lagoon-test/README.md, charts/lagoon-test/ci/linter-values.yaml, charts/lagoon-test/templates/NOTES.txt, charts/lagoon-test/templates/_helpers.tpl, charts/lagoon-test/templates/local-api-data-watcher-pusher.deployment.yaml, charts/lagoon-test/templates/local-git.deployment.yaml, charts/lagoon-test/templates/local-git.service.yaml, charts/lagoon-test/templates/secret.yaml, charts/lagoon-test/templates/test.clusterrolebinding.yaml, charts/lagoon-test/templates/test.serviceaccount.yaml, charts/lagoon-test/templates/tests/test-connection.yaml, charts/lagoon-test/templates/tests/test-suite.yaml, charts/lagoon-test/values.yaml, default.ct.yaml, test-suite-lint.ct.yaml, test-suite-run.ct.yaml, test-suite.kind-config.yaml
=> Add a lagoon-test chart

.github/pull_request_template.md
This template explains version-bump requirements for PRs, and prompts for a descriptive pull request.
=> Add pull-request template

charts/lagoon-logging/Chart.yaml, charts/lagoon-logging/templates/logs-dispatcher.fluent-conf.configmap.yaml, charts/lagoon-logging/values.yaml, charts/lagoon-logs-concentrator/Chart.yaml, charts/lagoon-logs-concentrator/templates/fluent-conf.configmap.yaml
this improves the flush performance of the whole logging system drastically, in my tests I had a container-log from a remote cluster within 20secs in kibana, while before this it took 3-4 minutes.
=> Flush performance

charts/lagoon-logging/Chart.lock, charts/lagoon-logging/Chart.yaml
Upgrade to the latest version of the logging-operator.
Closes: #116
=> Upgrade logging operator

charts/lagoon-core/Chart.yaml, charts/lagoon-core/ci/linter-values.yaml, charts/lagoon-test/Chart.yaml, charts/lagoon-test/ci/linter-values.yaml, charts/lagoon-test/values.yaml
Use the `main` image tag everywhere in CI instead of a custom branch build.
Closes: #121
=> Use "main" image tag instead of "lagoon-core"

.github/workflows/lint-test.yaml, Makefile, charts/lagoon-test/Chart.yaml, charts/lagoon-test/README.md, charts/lagoon-test/templates/local-api-data-watcher-pusher.deployment.yaml, test-suite.kind-config.yaml
This matches what we do in production.
Closes: #110
=> Use Harbor registry in CI

charts/lagoon-logs-concentrator/Chart.yaml, charts/lagoon-logs-concentrator/templates/fluent-conf.configmap.yaml
`suppress_type_name true` to have less warnings
=> Fluentd suppress warning

.github/workflows/lint-test.yaml
This PR fixes workflow errors in chart-testing-action v2.
=> Various fixes to github workflow for chart-testing-action@v2.0.0

charts/lagoon-logging/Chart.yaml, charts/lagoon-logging/README.md, charts/lagoon-logging/templates/_helpers.tpl, charts/lagoon-logging/templates/logs-dispatcher.fluent-conf.configmap.yaml, charts/lagoon-logging/templates/logs-dispatcher.service.yaml, charts/lagoon-logging/templates/logs-dispatcher.servicemonitor.yaml, charts/lagoon-logging/templates/logs-dispatcher.statefulset.yaml, charts/lagoon-logging/templates/openshift-haproxy-logs-collector.fluent-bit-conf.configmap.yaml, charts/lagoon-logging/templates/openshift-haproxy-logs-collector.service.yaml, charts/lagoon-logging/templates/openshift-haproxy-logs-collector.servicemonitor.yaml, charts/lagoon-logging/templates/openshift-haproxy-logs-collector.statefulset.yaml, charts/lagoon-logging/values.yaml, charts/lagoon-logs-concentrator/Chart.yaml, charts/lagoon-logs-concentrator/templates/servicemonitor.yaml
Uses @Schnitzel's technique of a fluentbit dedicated to haproxy router logs to avoid dropping logs.
=> Fix openshift haproxy logs

charts/lagoon-logging/Chart.yaml, charts/lagoon-logging/templates/openshift-haproxy-logs-collector.fluent-bit-conf.configmap.yaml, charts/lagoon-logging/templates/openshift-haproxy-logs-collector.statefulset.yaml
openshift does not like too long mount points
=> reduce length of openshiftHaproxyLogsCollector names

charts/lagoon-remote/Chart.yaml, charts/lagoon-remote/ci/linter-values.yaml, charts/lagoon-remote/values.yaml
Closes: #166, thanks @twardnw!
=> Increase the default size of the docker-host volume

charts/lagoon-remote/Chart.yaml, charts/lagoon-remote/values.yaml
Hopefully this will be enough to avoid out-of-space issues on busy clusters.
n/a
=> Increase default docker-host volume size

charts/lagoon-logging/Chart.yaml, charts/lagoon-logging/templates/logs-dispatcher.fluent-conf.configmap.yaml
Explain the **details** for making this change. What existing problem does the pull request solve?
Put `Closes: #XXXX` in your comment to auto-close the issue that your PR fixes (if such).
=> support for router logs with new ingress-nginx helmchart

Makefile, charts/lagoon-test/Chart.yaml, charts/lagoon-test/README.md
Various minor lagoon-test and CI improvements.
=> CI improvements

charts/lagoon-gatekeeper/Chart.yaml, charts/lagoon-gatekeeper/templates/constraint.job.yaml, charts/lagoon-gatekeeper/templates/psp-pods-allowed-user-ranges.constraint.yaml, charts/lagoon-gatekeeper/values.yaml
This PR automates the previous two-step process for correctly installing lagoon-gatekeeper by making use of chart hooks.
=> Automate constraint installation in lagoon-gatekeeper

charts/lagoon-gatekeeper/Chart.lock, charts/lagoon-gatekeeper/Chart.yaml, charts/lagoon-gatekeeper/templates/config.yaml
Upgrade gatekeeper chart dependency.
=> Upgrade gatekeeper dependency

charts/lagoon-remote/Chart.yaml, charts/lagoon-remote/templates/docker-host.deployment.yaml, charts/lagoon-remote/values.yaml
Linked PR in Lagoon
https://github.com/amazeeio/lagoon/pull/2368
Closes: #151
=> add update-images.sh for docker-host

Makefile
This doesn't appear to be used in any charts.
=> chore: remove unused variable from Makefile

charts/lagoon-logging/Chart.lock, charts/lagoon-logging/Chart.yaml
=> Bump lagoon-logging dependency on logging-operator

charts/lagoon-remote/Chart.lock, charts/lagoon-remote/Chart.yaml, charts/lagoon-remote/templates/docker-host.clusterrole.yaml, charts/lagoon-remote/templates/docker-host.rolebinding.yaml, charts/lagoon-remote/values.yaml
Explain the **details** for making this change. What existing problem does the pull request solve?
Put `Closes: #XXXX` in your comment to auto-close the issue that your PR fixes (if such).
=> lagoon-remote docker-host openshift support

charts/lagoon-build-deploy/Chart.yaml, charts/lagoon-build-deploy/crds/lagoonBuild.yaml
This is to replace #245 so the same issues with the CRD update will apply here. (https://github.com/uselagoon/lagoon-charts/pull/245#pullrequestreview-625133433)
=> Update builddeploy controller to v0.1.9

charts/lagoon-core/Chart.yaml, charts/lagoon-logging/Chart.yaml, charts/lagoon-logs-concentrator/Chart.yaml, charts/lagoon-remote/Chart.yaml, charts/lagoon-test/Chart.yaml
This PR updates the Lagoon charts for the recently released https://github.com/amazeeio/lagoon/releases/tag/v2.0.0-alpha.8
=> v2.0.0-alpha.8 updates

Makefile
=> Bump CI chart dependencies

charts/lagoon-build-deploy/Chart.yaml
=> bump lagoon kbd to latest v0.1.12

Makefile
This option can be used in uselagoon/lagoon CI to avoid installing the registry twice.
=> Add option to skip installing the registry

charts/lagoon-core/Chart.yaml, charts/lagoon-logging/Chart.yaml, charts/lagoon-logs-concentrator/Chart.yaml, charts/lagoon-remote/Chart.yaml, charts/lagoon-test/Chart.yaml
Matching lagoon-charts release for https://github.com/uselagoon/lagoon/releases/tag/v2.0.0-rc.2
=> update appVersion to v2.0.0-rc.2

Makefile
The install-tests target was installing the lagoon-test chart manually, which breaks assumptions in the helm chart-testing tooling and also breaks `kind/retest` in the `uselagoon/lagoon` Makefile.
So remove that target and instead update the fill-test-ci-values target to do the thing that install-tests was intended to do.
=> Remove install-tests target from Makefile

charts/lagoon-build-deploy/Chart.yaml
=> update lagoon-build-deploy to v0.1.15

.github/workflows/lint-test.yaml, .github/workflows/test-suite.yaml
defaults kind to 0.11.1 and kubectl to 1.20.8
=> use kind-action 1.2.0 for github actions

charts/lagoon-core/Chart.yaml, charts/lagoon-logging/Chart.yaml, charts/lagoon-logs-concentrator/Chart.yaml, charts/lagoon-remote/Chart.yaml, charts/lagoon-test/Chart.yaml
Lagoon https://github.com/uselagoon/lagoon/releases/tag/v2.0.0-rc.5 has been released, this updates the charts accordingly
=> update appVersion to release v2.0.0-rc.5

charts/lagoon-logging/Chart.yaml, charts/lagoon-logging/ci/linter-values.yaml, charts/lagoon-logging/templates/logs-dispatcher.statefulset.yaml, charts/lagoon-logging/values.yaml
This adds options for:
* size
* storageClass
Closes: #180
=> Make the logs-dispatcher statefulset volumeTemplate configurable

charts/lagoon-build-deploy/Chart.yaml, charts/lagoon-build-deploy/README.md
=> Add README for lagoon-build-deploy chart

charts/lagoon-core/Chart.yaml, charts/lagoon-logging/Chart.yaml, charts/lagoon-logs-concentrator/Chart.yaml, charts/lagoon-remote/Chart.yaml, charts/lagoon-test/Chart.yaml
Matches https://github.com/uselagoon/lagoon/releases/tag/v2.0.0-rc.6
=> update appVersion to v2.0.0-rc.6

charts/lagoon-core/Chart.yaml, charts/lagoon-logging/Chart.yaml, charts/lagoon-logs-concentrator/Chart.yaml, charts/lagoon-remote/Chart.yaml, charts/lagoon-test/Chart.yaml
=> update to lagoon-core rc7

charts/lagoon-core/Chart.yaml, charts/lagoon-logging/Chart.yaml, charts/lagoon-logs-concentrator/Chart.yaml, charts/lagoon-remote/Chart.yaml, charts/lagoon-test/Chart.yaml
https://github.com/uselagoon/lagoon/releases/tag/v2.0.0-rc.8
=> update to appVersion 2.0.0-rc.8

.github/workflows/lint-test.yaml, charts/lagoon-logging/Chart.lock, charts/lagoon-logging/Chart.yaml
Upgrade dependency to latest version.
=> Bump logging-operator chart dependency in lagoon-logging chart

charts/lagoon-core/Chart.yaml, charts/lagoon-core/README.md, charts/lagoon-core/ci/linter-values.yaml, charts/lagoon-core/templates/api.deployment.yaml, charts/lagoon-core/templates/auto-idler.deployment.yaml, charts/lagoon-core/values.yaml, charts/lagoon-logging/Chart.yaml, charts/lagoon-logs-concentrator/Chart.yaml, charts/lagoon-remote/Chart.yaml, charts/lagoon-test/Chart.yaml
Updated Lagoon-charts to match release - https://github.com/uselagoon/lagoon/releases/tag/v2.0.0-rc.9
=> update appVersion to v2.0.0-rc.9 release

charts/lagoon-logs-concentrator/Chart.yaml, charts/lagoon-logs-concentrator/templates/fluent-conf.configmap.yaml
This changes reduces noise in the lagoon-logs-concentrator logs.
=> Quiet liveness probes

charts/lagoon-core/Chart.yaml, charts/lagoon-logging/Chart.yaml, charts/lagoon-logs-concentrator/Chart.yaml, charts/lagoon-remote/Chart.yaml, charts/lagoon-test/Chart.yaml
Charts update for https://github.com/uselagoon/lagoon/releases/tag/v2.0.0
=> Lagoon 2.0.0 appVersion

charts/lagoon-core/Chart.yaml, charts/lagoon-logging/Chart.yaml, charts/lagoon-logs-concentrator/Chart.yaml, charts/lagoon-remote/Chart.yaml, charts/lagoon-test/Chart.yaml
matching chart release for https://github.com/uselagoon/lagoon/releases/tag/v2.2.1
=> Update to Lagoon appVersion: v2.2.1

charts/lagoon-core/Chart.yaml, charts/lagoon-logging/Chart.yaml, charts/lagoon-logs-concentrator/Chart.yaml, charts/lagoon-remote/Chart.yaml, charts/lagoon-test/Chart.yaml
Chart release for https://github.com/uselagoon/lagoon/releases/tag/v2.2.3
=> appVersion: v2.2.3

charts/lagoon-core/Chart.yaml, charts/lagoon-logging/Chart.yaml, charts/lagoon-logs-concentrator/Chart.yaml, charts/lagoon-remote/Chart.yaml, charts/lagoon-test/Chart.yaml
https://github.com/uselagoon/lagoon/releases/tag/v2.2.4
=> update to appVersion: v2.2.4

.github/workflows/test-suite.yaml, charts/lagoon-core/Chart.yaml, charts/lagoon-logging/Chart.yaml, charts/lagoon-logs-concentrator/Chart.yaml, charts/lagoon-remote/Chart.yaml, charts/lagoon-remote/templates/docker-host.deployment.yaml, charts/lagoon-remote/values.yaml, charts/lagoon-test/Chart.yaml
Also added PRUNE_IMAGES_UNTIL env var to docker-host
Release at https://github.com/uselagoon/lagoon/releases/tag/v2.3.0
=> Lagoon v2.3.0 release

charts/lagoon-build-deploy/Chart.yaml, charts/lagoon-build-deploy/crds/crd.lagoon.sh_lagoonbuilds.yaml, charts/lagoon-build-deploy/crds/crd.lagoon.sh_lagoontasks.yaml, charts/lagoon-build-deploy/crds/lagoonBuild.yaml, charts/lagoon-build-deploy/templates/NOTES.txt, charts/lagoon-build-deploy/templates/deployment.yaml, charts/lagoon-build-deploy/values.yaml
=> Update remote-controller to v0.2.0

charts/lagoon-remote/Chart.lock, charts/lagoon-remote/Chart.yaml
=> Update lagoon-remote to use latest lagoon-build-deploy chart

Makefile
=> Expose keycloak and api to ui so ui for local development V2

charts/lagoon-build-deploy/Chart.yaml, charts/lagoon-build-deploy/crds/lagoonBuild.yaml, charts/lagoon-build-deploy/templates/NOTES.txt
=> Minor build-deploy chart fixes

charts/lagoon-remote/Chart.lock, charts/lagoon-remote/Chart.yaml
=> Update lagoon-remote to use latest lagoon-build-deploy

charts/lagoon-build-deploy/Chart.yaml, charts/lagoon-build-deploy/crds/crd.lagoon.sh_lagoonbuilds.yaml, charts/lagoon-build-deploy/crds/crd.lagoon.sh_lagoontasks.yaml
=> update crds for additional metadata and use supporting version of remote-controller

charts/lagoon-remote/Chart.lock, charts/lagoon-remote/Chart.yaml
=> use lagoon-build-deploy 0.8.2

charts/lagoon-remote/Chart.lock, charts/lagoon-remote/Chart.yaml, charts/lagoon-remote/templates/dbaas.service.yaml, charts/lagoon-remote/values.yaml
=> update dbaas-operator chart and add the dbaas http lagoon service

charts/lagoon-build-deploy/Chart.yaml, charts/lagoon-build-deploy/templates/deployment.yaml, charts/lagoon-build-deploy/values.yaml
=> Add the rwx to rwo feature flag

charts/lagoon-remote/Chart.yaml, charts/lagoon-remote/templates/docker-host.deployment.yaml, charts/lagoon-remote/values.yaml
=> Add support for extra variable injection to docker-host

charts/lagoon-build-deploy/Chart.yaml, charts/lagoon-build-deploy/templates/deployment.yaml, charts/lagoon-build-deploy/values.yaml
=> Add proxy config to lagoon-build-deploy

charts/lagoon-remote/Chart.yaml, charts/lagoon-remote/templates/docker-host.deployment.yaml, charts/lagoon-remote/values.yaml
=> Add proxy config to lagoon-remote chart

charts/lagoon-remote/Chart.lock, charts/lagoon-remote/Chart.yaml, charts/lagoon-remote/values.yaml
This simply updates the dependencies for insights remote and build-deploy
=> Updates lagoon-remote chart depdendencies

charts/lagoon-build-deploy/Chart.yaml
=> update remote-controller to v0.2.4

charts/lagoon-remote/Chart.lock, charts/lagoon-remote/Chart.yaml
=> update lagoon-remote with latest build-deploy chart

charts/lagoon-build-deploy/Chart.yaml, charts/lagoon-build-deploy/crds/crd.lagoon.sh_lagoontasks.yaml
=> Remove openshiftProjectName from tasks crd

charts/lagoon-remote/Chart.lock, charts/lagoon-remote/Chart.yaml
=> update lagoon-remote to use latest remote controller version

Makefile, charts/lagoon-core/Chart.yaml, charts/lagoon-core/ci/linter-values.yaml, charts/lagoon-logging/Chart.yaml, charts/lagoon-logs-concentrator/Chart.yaml, charts/lagoon-remote/Chart.yaml, charts/lagoon-test/Chart.yaml
lagoon-charts release to match https://github.com/uselagoon/lagoon/releases/tag/v2.5.0
=> lagoon-core appVersion: v2.5.0

charts/lagoon-core/Chart.yaml, charts/lagoon-core/templates/insights-handler.deployment.yaml, charts/lagoon-core/templates/insights-handler.hpa.yaml, charts/lagoon-core/values.yaml
=> Minor updates to insights-core templates to match others

charts/lagoon-remote/Chart.lock, charts/lagoon-remote/Chart.yaml
=> Lagoon remote 0.51.0

charts/lagoon-core/Chart.yaml, charts/lagoon-logging/Chart.yaml, charts/lagoon-logs-concentrator/Chart.yaml, charts/lagoon-remote/Chart.yaml, charts/lagoon-test/Chart.yaml
Corresponding chart release for https://github.com/uselagoon/lagoon/releases/tag/v2.7.0
=> update lagoon-core for appVersion: v2.7.0

charts/lagoon-build-deploy/Chart.yaml, charts/lagoon-build-deploy/templates/deployment.yaml, charts/lagoon-build-deploy/values.yaml
=> chore: update remote-controller to use latest version

charts/lagoon-core/Chart.yaml, charts/lagoon-logging/Chart.yaml, charts/lagoon-logs-concentrator/Chart.yaml, charts/lagoon-remote/Chart.lock, charts/lagoon-remote/Chart.yaml, charts/lagoon-test/Chart.yaml
lagoon-charts to match https://github.com/uselagoon/lagoon/releases/tag/v2.8.0
=> appVersion: v2.8.0

charts/lagoon-core/Chart.yaml
lagoon-core only release for https://github.com/uselagoon/lagoon/releases/tag/v2.8.1
=> lagoon-core appVersion: v2.8.1

charts/lagoon-core/Chart.yaml
lagoon-core only release for https://github.com/uselagoon/lagoon/releases/tag/v2.8.4
=> lagoon-core v2.8.4 appVersions

charts/lagoon-core/Chart.yaml, charts/lagoon-logging/Chart.yaml, charts/lagoon-logs-concentrator/Chart.yaml, charts/lagoon-remote/Chart.lock, charts/lagoon-remote/Chart.yaml, charts/lagoon-test/Chart.yaml
lagoon release to match https://github.com/uselagoon/lagoon/releases/tag/v2.9.0
=> appVersion: v2.9.0

charts/lagoon-build-deploy/Chart.yaml, charts/lagoon-build-deploy/crds/crd.lagoon.sh_lagoonbuilds.yaml, charts/lagoon-build-deploy/crds/crd.lagoon.sh_lagoontasks.yaml
After installing this version, update the CRDs with
```
helm show crds lagoon/lagoon-build-deploy --version 0.14.0 | kubectl apply -f -
```
=> Update lagoon-remote CRDs

charts/lagoon-core/Chart.yaml, charts/lagoon-core/templates/api-db.statefulset.yaml, charts/lagoon-core/values.yaml
This is intended to help automatically recover from the case where the api-db pod becomes unresponsive.
=> Improve probes on api-db pod

charts/lagoon-core/Chart.yaml, charts/lagoon-core/templates/api-db.statefulset.yaml, charts/lagoon-core/values.yaml, charts/lagoon-remote/Chart.yaml, charts/lagoon-remote/values.yaml
This version fixes https://github.com/uselagoon/lagoon-ssh-portal/issues/103
=> Bump ssh-portal version

charts/lagoon-build-deploy/Chart.yaml, charts/lagoon-build-deploy/crds/crd.lagoon.sh_lagoonbuilds.yaml, charts/lagoon-build-deploy/templates/deployment.yaml, charts/lagoon-build-deploy/values.yaml
Update the remote-controller to the latest version.
Add new values to support controller options for harbor and namespace cleanup processes
=> chore: bump remote-controller, add new controller options

charts/lagoon-core/Chart.yaml, charts/lagoon-core/values.yaml
logs2notifications was incorrectly pointing at testlagoon/logs2notifications:main
=> use uselagoon for logs2notifications

charts/lagoon-logging/Chart.yaml, charts/lagoon-logging/values.yaml
Add support for logs collection from spot instances.
=> Spot logging

charts/lagoon-logging/Chart.yaml, charts/lagoon-logging/values.yaml
source PR - https://github.com/uselagoon/lagoon-service-images/pull/9
=> update logs-dispatcher image to v3.1.0

charts/lagoon-insights-remote/Chart.yaml, charts/lagoon-insights-remote/README.md
Lagoon Insights Remote is being added as a service in #518
=> deprecate lagoon-insights-remote chart

charts/lagoon-build-deploy/Chart.yaml
=> chore: bump the remote-controller to latest version v0.7.2

charts/lagoon-logging/Chart.yaml, charts/lagoon-logging/ci/linter-values.yaml, charts/lagoon-logging/templates/logs-dispatcher.fluent-conf.configmap.yaml, charts/lagoon-logging/templates/tests/test-connection.yaml, charts/lagoon-logging/templates/tests/test-logs-dispatcher-processing.yaml, charts/lagoon-logging/values.yaml
Add a test suite for lagoon-logging, and bump the logs-dispatcher image for better compatibility with recent k8s versions.
See https://github.com/uselagoon/lagoon-service-images/pull/10
=> Lagoon logging tests

.github/workflows/lint-test.yaml
Add a CI check that the artifacthub changelog has been updated.
=> Artifacthub changelog check

charts/lagoon-remote/Chart.yaml, charts/lagoon-remote/templates/ssh-portal.service.yaml, charts/lagoon-remote/values.yaml
=> Added annotations support to ssh-portal service

charts/lagoon-core/Chart.yaml, charts/lagoon-core/values.yaml, charts/lagoon-remote/Chart.yaml, charts/lagoon-remote/values.yaml
Fixes https://github.com/uselagoon/lagoon-ssh-portal/issues/162
=> Bump ssh-portal version in lagoon-remote and lagoon-core

charts/lagoon-core/Chart.yaml, charts/lagoon-test/Chart.yaml
core and test chart releases for https://github.com/uselagoon/lagoon/releases/tag/v2.13.0
=> update Lagoon appVersion to v2.13.0

charts/lagoon-build-deploy/Chart.yaml, charts/lagoon-build-deploy/templates/deployment.yaml, charts/lagoon-build-deploy/values.yaml
Support for https://github.com/uselagoon/build-deploy-tool/issues/198
=> feat: add ephemeral storage limit configuration w/ update to remote-controller

charts/lagoon-core/Chart.yaml, charts/lagoon-test/Chart.yaml
Chart release for https://github.com/uselagoon/lagoon/releases/tag/v2.14.2
=> update Lagoon appVersion to v2.14.2

charts/lagoon-core/Chart.yaml, charts/lagoon-test/Chart.yaml, test-suite-lint.ct.yaml, test-suite-run.ct.yaml
chart release for https://github.com/uselagoon/lagoon/releases/tag/v2.15.0
=> update Lagoon appVersion to v2.15.0

charts/lagoon-remote/Chart.lock, charts/lagoon-remote/Chart.yaml, charts/lagoon-remote/values.yaml
=> chore: update build-deploy subchart to v0.23.0

charts/lagoon-build-deploy/Chart.yaml
=> chore: update remote-controller to v0.13.1

charts/lagoon-core/Chart.yaml, charts/lagoon-test/Chart.yaml
Corresponding release for https://github.com/uselagoon/lagoon/releases/tag/v2.15.1
=> update Lagoon appVersion to v2.15.1

charts/lagoon-core/Chart.yaml, charts/lagoon-test/Chart.yaml
Lagoon-charts release to match https://github.com/uselagoon/lagoon/releases/tag/v2.15.2
=> update Lagoon appVersion to v2.15.2

charts/lagoon-build-deploy/Chart.yaml, charts/lagoon-build-deploy/crds/crd.lagoon.sh_lagoontasks.yaml
=> chore: update remote-controller and bump crd for tasks

charts/lagoon-remote/Chart.lock, charts/lagoon-remote/Chart.yaml
=> chore: update lagoon-build-deploy to v0.24.0

charts/lagoon-core/Chart.yaml, charts/lagoon-test/Chart.yaml
lagoon core/test release for https://github.com/uselagoon/lagoon/releases/tag/v2.15.3
=> update Lagoon appVersion to v2.15.3

charts/lagoon-core/Chart.lock, charts/lagoon-core/Chart.yaml, charts/lagoon-core/templates/broker.servicemonitor.yaml, charts/lagoon-core/values.yaml, charts/lagoon-remote/Chart.lock, charts/lagoon-remote/Chart.yaml, charts/lagoon-remote/values.yaml, charts/lagoon-test/Chart.yaml
Lagoon charts release for https://github.com/uselagoon/lagoon/releases/tag/v2.15.4
=> update Lagoon appVersion to v2.15.4

charts/lagoon-build-deploy/Chart.yaml
=> chore: bump remote-controller to v0.15.1

charts/lagoon-build-deploy/Chart.yaml, charts/lagoon-build-deploy/templates/deployment.yaml, charts/lagoon-build-deploy/values.yaml
=> chore: update remote-controller to v0.15.2

charts/lagoon-remote/Chart.lock, charts/lagoon-remote/Chart.yaml
=> chore: update lagoon-build-deploy to v0.25.2

charts/lagoon-build-deploy/Chart.yaml
=> chore: bump remote-controller to v0.15.3

charts/lagoon-core/Chart.yaml, charts/lagoon-core/values.yaml
=> Bump lagoon-opensearch-sync

charts/lagoon-build-deploy/Chart.yaml
=> chore: bump remote-controller to v0.15.4

charts/lagoon-remote/Chart.yaml, charts/lagoon-remote/ci/linter-values.yaml, charts/lagoon-remote/templates/ssh-portal.clusterrole.yaml, charts/lagoon-remote/templates/ssh-portal.deployment.yaml, charts/lagoon-remote/values.yaml
- feat: add support for logs access via SSH
- chore: bump lagoon-remote chart version
- chore: enable log access in ci values
Closes: #644
=> feat: add log streaming option to ssh-portal

charts/lagoon-build-deploy/Chart.yaml
=> chore: bump remote-controller to v0.15.7

Makefile
Small fix to the unauthenticated registry to configure the certificate properly for the ingress.
=> fix: unauthenticated registry tls

charts/lagoon-core/Chart.lock, charts/lagoon-core/Chart.yaml, charts/lagoon-remote/Chart.yaml, charts/lagoon-test/Chart.yaml
lagoon charts release for Lagoon Core 2.24 - https://docs.lagoon.sh/releases/2.24.0/
=> update lagoon appVersion to v2.24.0

charts/lagoon-build-deploy/Chart.yaml, charts/lagoon-build-deploy/templates/deployment.yaml
=> fix: verifypeer reference with quotes

charts/lagoon-remote/Chart.lock, charts/lagoon-remote/Chart.yaml, charts/lagoon-remote/templates/insights-remote.deployment.yaml, charts/lagoon-remote/templates/storage-calculator.deployment.yaml
Updates the lagoon-build-deploy subchart to recently released v0.34.x
=> chore: update lagoon-build-deploy subchart to v0.34.x

Makefile
Fixes a small issue where the `lagoon-build-deploy` chart which is now configured in CI to install with broker tls enabled but has been released. When the `lagoon-core` installation in the uselagoon/lagoon repo installs the stable version prior to the upcoming release which contains broker enabled by default, the `lagoon-build-deploy` chart won't connect.
This forces the lagoon-build-deploy chart to install without broker tls if the version of lagoon-core is older than 1.52.0 which is the last version that supported non-tls installations in CI by default
=> test: disable tls in lagoon-build-deploy for older stable core

charts/lagoon-build-deploy/Chart.yaml
Update remote-controller to v0.24.0 and release the chart.
=> Updates remote-controller to v0.24.0

charts/lagoon-logging/Chart.yaml, charts/lagoon-logging/templates/cdn-logs-collector-metrics.service.yaml, charts/lagoon-logging/values.yaml
Add additional service to expose cdn-logs-collector metrics
=> add service for cdn-logs-collector metrics

Makefile
#793 changed the way that nats certificates were installed when used in CI or the `uselagoon/lagoon` local-stack. This broke the upgrade from a `k3d/stable-install-lagoon` to `k3d/install-lagoon` as the prior versions installed the certificates via the chart. When the target is run, the core and remote NATS certificates secrets would be created, then the stable version would attempt to install its version but would fail as the secret already exists. Additionally, when the upgrade occurs, the certificates would be removed by helm and break the ssh-portal as the CA certificate is still required.
This fixes that by checking which version of the stable chart is being installed before creating the nats secrets, and also by re-running the certs for remote after installation to ensure that the …
=> chore: fix stable-stack nats certs

.gitignore, Makefile, ci/default-ingress-certificate-request.yaml.tpl
Configures a default wildcard certificate to ingress-nginx for local development
=> chore: add default certificate for ingress

charts/lagoon-remote/Chart.yaml, charts/lagoon-remote/values.yaml
Update storage calculator to v0.8.1
And fix small typo :see_no_evil:
=> chore: update storage calculator to v0.8.1

Makefile
The previous version checks used by local-stack had some cases that didn't work properly. This refactors to use `jq` to do the version check instead.
=> chore: use jq to compare chart versions for local-stack
